const lessonContents =     [
    {
        order_number: 1,
        content_type: "heading",
        content: "តើការរចនាការស្រាវជ្រាវជាអ្វី?",
        lessonId: 1,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការរចនាការស្រាវជ្រាវគឺជាផែនការរួមសម្រាប់ការប្រមូល, វាស់វែង, និងវិភាគទិន្នន័យ។ វាជាផែនទីដែលណែនាំការសិក្សារបស់អ្នកពីដើមដល់ចប់។ វារៀបរាប់ពីវិធីសាស្ត្រ និងបច្ចេកទេសដែលអ្នកនឹងប្រើដើម្បីដោះស្រាយបញ្ហាស្រាវជ្រាវរបស់អ្នក។ ការរចនាដ៏ល្អធានានូវភាពត្រឹមត្រូវ និងភាពជឿជាក់នៃលទ្ធផលរបស់អ្នក។",
        lessonId: 1,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 1,
    },
    {
        order_number: 4,
        content_type: "heading",
        content: "ប្រភេទនៃការរចនាស្រាវជ្រាវ",
        lessonId: 1,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការរចនាបរិមាណ (Quantitative Design): ផ្តោតលើការប្រមូលនិងវិភាគទិន្នន័យលេខ។",
        lessonId: 1,
    },
    {
        order_number: 6,
        content_type: "list",
        content: "ការរចនាគុណភាព (Qualitative Design): ផ្តោតលើការប្រមូលនិងវិភាគទិន្នន័យអត្ថបទឬរូបភាព។",
        lessonId: 1,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់វិធីសាស្រ្តស្ទង់មតិ",
        lessonId: 2,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "វិធីសាស្រ្តស្ទង់មតិត្រូវបានប្រើដើម្បីប្រមូលទិន្នន័យពីមនុស្សមួយចំនួនធំ ដូចជាសាធារណជនទូទៅ ឬក្រុមគោលដៅជាក់លាក់។ ឧបករណ៍ធម្មតាគឺកម្រងសំណួរឬការសម្ភាសន៍តាមទូរស័ព្ទ។",
        lessonId: 2,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://www.zonkafeedback.com/hubfs/Untitled%20design%20%2812%29.png",
        lessonId: 2,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "កម្រងសំណួរត្រូវរៀបចំដោយប្រុងប្រយ័ត្នដើម្បីចៀសវាងភាពលម្អៀង។",
        lessonId: 2,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "លទ្ធផលអាចត្រូវបានប្រើដើម្បីធ្វើការទូទៅចំពោះប្រជាជនទាំងមូល។",
        lessonId: 2,
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://scontent.fpnh5-3.fna.fbcdn.net/v/t39.30808-6/488004560_1084752257024626_1139644088342440346_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=127cfc&_nc_ohc=Ql_mvvjE2lAQ7kNvwFRka9I&_nc_oc=AdlSMIF42ZHxHTUSz_mCbKVYdPw3ffCQ7BMT8I_9juzxVHJug5WTK5s5RSTHdQCLUm8&_nc_zt=23&_nc_ht=scontent.fpnh5-3.fna&_nc_gid=zCg4m6eCjUwwh26Vd5C0Rg&oh=00_AfZ-XoWlXsc8bKUVKMQ7YFvIpzBZSTTdeA52SQHTz7qb9A&oe=68CC08E0",
        lessonId: 2,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរៀបចំការពិសោធន៍",
        lessonId: 3,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ក្នុងការពិសោធន៍ អ្នកស្រាវជ្រាវគ្រប់គ្រងអថេរឯករាជ្យដើម្បីសង្កេតមើលឥទ្ធិពលលើអថេរអាស្រ័យ។ នេះអនុញ្ញាតឱ្យកំណត់ទំនាក់ទំនងមូលហេតុនិងលទ្ធផល។",
        lessonId: 3,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://cdn.prod.website-files.com/619e15d781b21202de206fb5/62f62b00791f0a712a693a46_Core-Benefits-of-Automated-Testing-in-App-Development.webp",
        lessonId: 3,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាត្រូវការក្រុមត្រួតពិនិត្យ និងក្រុមពិសោធន៍។",
        lessonId: 3,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វាមានប្រយោជន៍សម្រាប់សាកល្បងសម្មតិកម្ម។",
        lessonId: 3,
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2015/04/usertesting.jpg",
        lessonId: 3,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសង្កេត និងការសម្ភាសន៍",
        lessonId: 4,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការសង្កេត និងការសម្ភាសន៍ត្រូវបានប្រើប្រាស់ដើម្បីប្រមូលទិន្នន័យលម្អិត។ ការសង្កេតអាចមានលក្ខណៈសាមញ្ញឬរៀបចំជាប្រព័ន្ធ។",
        lessonId: 4,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://bizkhmer.com/storage/articles/Da0yV8wXni6pKz6hFkfRKwx6d5ois8fkUTQRjgQb.jpeg",
        lessonId: 4,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការសម្ភាសន៍អាចមានលក្ខណៈរៀបចំជាប្រព័ន្ធ ឬមិនរៀបចំជាប្រព័ន្ធ។",
        lessonId: 4,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វិធីសាស្ត្រទាំងនេះជួយយល់ពីទស្សនៈនិងបទពិសោធន៍ផ្ទាល់ខ្លួន។",
        lessonId: 4,
    },
    {
        order_number: 6,
        content_type: "space",
        content: "",
        lessonId: 4,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ជំហានក្នុងការសម្អាតទិន្នន័យ",
        lessonId: 5,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "មុនពេលវិភាគ អ្នកត្រូវពិនិត្យមើលទិន្នន័យសម្រាប់កំហុសដូចជា តម្លៃបាត់ តម្លៃមិនត្រឹមត្រូវ ឬទម្រង់មិនស៊ីគ្នា។",
        lessonId: 5,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 5,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "កំណត់អត្តសញ្ញាណតម្លៃមិនប្រក្រតី (outliers)។",
        lessonId: 5,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "បំពេញតម្លៃដែលបាត់ដោយវិធីសាស្ត្រសមស្រប។",
        lessonId: 5,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ហេតុអ្វីត្រូវធ្វើទ្រង់ទ្រាយទិន្នន័យ?",
        lessonId: 6,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការធ្វើទ្រង់ទ្រាយទិន្នន័យឱ្យមានលក្ខណៈឯកសណ្ឋានជួយកម្មវិធីវិភាគដំណើរការទិន្នន័យបានត្រឹមត្រូវ។ វាជាជំហានចាំបាច់ដើម្បីធានាថាទិន្នន័យរបស់អ្នកត្រៀមរួចជាស្រេចសម្រាប់ការវិភាគ។",
        lessonId: 6,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 6,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "បំប្លែងទម្រង់កាលបរិច្ឆេទនិងពេលវេលាឱ្យដូចគ្នា។",
        lessonId: 6,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "បំប្លែងតម្លៃទៅជាលេខសម្រាប់វិភាគ។",
        lessonId: 6,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "តើអ្វីទៅជាតារាងចែកចាយប្រេកង់?",
        lessonId: 7,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "តារាងនេះបង្ហាញពីភាពញឹកញាប់នៃតម្លៃនីមួយៗក្នុងទិន្នន័យរបស់អ្នក។ វាមានប្រយោជន៍សម្រាប់ការសង្ខេបទិន្នន័យ។",
        lessonId: 7,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://i.ytimg.com/vi/dC4p5YZkw8o/maxresdefault.jpg",
        lessonId: 7,
    },
    {
        order_number: 4,
        content_type: "text",
        content: "តារាងចែកចាយប្រេកង់ (Frequency Distribution Table) គឺជាតារាងដែលបង្ហាញពីភាពញឹកញាប់នៃតម្លៃនីមួយៗក្នុងសំណុំទិន្នន័យ។",
        lessonId: 7,
    },
    {
        order_number: 5,
        content_type: "list",   
        content: "វាមានជួរឈរសម្រាប់ប្រភេទនិងភាពញឹកញាប់។",
        lessonId: 7,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ប្រភេទនៃក្រាហ្វ",
        lessonId: 8,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "ក្រាហ្វរបារ (Bar Chart) សម្រាប់ការប្រៀបធៀបប្រភេទផ្សេងៗ។",
        lessonId: 8,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "ក្រាហ្វប្រេកង់ (Histogram) សម្រាប់ការបង្ហាញការចែកចាយទិន្នន័យ។",
        lessonId: 8,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 8,
    },
    {
        order_number: 5,
        content_type: "space",
        content: "",
        lessonId: 8,
    },
    {
        order_number: 6,
        content_type: "text",
        content: "ការបង្ហាញក្រាហ្វិកជួយអ្នកអានយល់ពីលំនាំទិន្នន័យយ៉ាងរហ័ស។",
        lessonId: 8,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបគណនាមធ្យមភាគ",
        lessonId: 9,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដើម្បីគណនាមធ្យមភាគ (Mean) អ្នកត្រូវបូកតម្លៃទាំងអស់ក្នុងសំណុំទិន្នន័យហើយចែកនឹងចំនួនតម្លៃសរុប។ វាជារង្វាស់នៃទំនោរកណ្តាលដែលត្រូវបានប្រើប្រាស់ទូទៅបំផុត។",
        lessonId: 9,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "ឧទាហរណ៍: (2 + 4 + 6 + 8) / 4 = 5",
        lessonId: 9,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 9,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "មធ្យមភាគងាយស្រួលគណនា ប៉ុន្តែវាអាចរងផលប៉ះពាល់ដោយតម្លៃមិនប្រក្រតី (outliers)។",
        lessonId: 9,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបរកឌីយ៉ង់",
        lessonId: 10,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំបូងអ្នកត្រូវតម្រៀបទិន្នន័យពីតូចទៅធំ។ បន្ទាប់មក រកតម្លៃដែលស្ថិតនៅចំកណ្តាល។",
        lessonId: 10,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 10,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ឧទាហរណ៍៖ សំណុំទិន្នន័យ (1, 3, 5, 8, 9) ឌីយ៉ង់គឺ 5។",
        lessonId: 10,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "ឌីយ៉ង់មិនរងផលប៉ះពាល់ដោយតម្លៃមិនប្រក្រតី ដូច្នេះវាល្អសម្រាប់ទិន្នន័យមិនស្មើគ្នា។",
        lessonId: 10,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់មូលដ្ឋាន",
        lessonId: 11,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "មូលដ្ឋាន (Mode) គឺជាតម្លៃដែលកើតឡើងញឹកញាប់បំផុត។ វាអាចប្រើសម្រាប់ទាំងទិន្នន័យគុណភាពនិងបរិមាណ។",
        lessonId: 11,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 11,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ឧទាហរណ៍៖ សំណុំទិន្នន័យ (1, 2, 2, 3, 4) មូលដ្ឋានគឺ 2។",
        lessonId: 11,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "អ្នកអាចមានមូលដ្ឋានច្រើនជាងមួយ ប្រសិនបើតម្លៃពីរឬច្រើនមានភាពញឹកញាប់ដូចគ្នា។",
        lessonId: 11,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ពេលណាត្រូវប្រើមធ្យមភាគ ឌីយ៉ង់ ឬមូលដ្ឋាន",
        lessonId: 12,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "មធ្យមភាគ៖ ល្អបំផុតសម្រាប់ទិន្នន័យបរិមាណដែលមានការចែកចាយធម្មតា។",
        lessonId: 12,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "ឌីយ៉ង់៖ ល្អបំផុតសម្រាប់ទិន្នន័យដែលមានតម្លៃមិនប្រក្រតី។",
        lessonId: 12,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "មូលដ្ឋាន៖ ល្អបំផុតសម្រាប់ទិន្នន័យគុណភាពឬប្រភេទ។",
        lessonId: 12,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "សម្មតិកម្ម Null (H₀)",
        lessonId: 13,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សម្មតិកម្ម Null តំណាងឱ្យសេចក្តីថ្លែងការណ៍ដែលគ្មានទំនាក់ទំនងឬភាពខុសគ្នា។ វាជាសម្មតិកម្មដែលអ្នកព្យាយាមបដិសេធ។",
        lessonId: 13,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 13,
    },
    {
        order_number: 4,
        content_type: "heading",
        content: "សម្មតិកម្មជំនួស (Hₐ)",
        lessonId: 13,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "សម្មតិកម្មជំនួសតំណាងឱ្យសេចក្តីថ្លែងការណ៍ដែលអ្នកចង់បង្ហាញថាត្រឹមត្រូវ។ វាផ្ទុយពីសម្មតិកម្ម null។",
        lessonId: 13,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការយល់ដឹងអំពី Alpha",
        lessonId: 14,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "កម្រិតន័យសំខាន់ (α) គឺជាប្រូបាប៊ីលីតេនៃការបដិសេធសម្មតិកម្ម null នៅពេលដែលវាមិនពិត។ វាគឺជាកម្រិតនៃហានិភ័យដែលអ្នកស្រាវជ្រាវយល់ព្រមទទួលយក។",
        lessonId: 14,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 14,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 14,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ប្រសិនបើ α=0.05 នោះមានហានិភ័យ 5% នៃការបដិសេធសម្មតិកម្ម null មិនត្រឹមត្រូវ។",
        lessonId: 14,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការយល់ដឹងអំពី P-Value",
        lessonId: 15,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "P-value គឺជាប្រូបាប៊ីលីតេនៃការទទួលបានលទ្ធផលដែលអ្នកទទួលបាន ឬលទ្ធផលដែលខ្លាំងជាងនេះ ប្រសិនបើសម្មតិកម្ម null ត្រឹមត្រូវ។ P-value តូចបង្ហាញពីភស្តុតាងរឹងមាំប្រឆាំងនឹងសម្មតិកម្ម null។",
        lessonId: 15,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "P-value តិចជាង 0.05 ជាធម្មតាត្រូវបានចាត់ទុកថាមានសារៈសំខាន់ជាស្ថិតិ។",
        lessonId: 15,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 15,
    },
    {
        order_number: 5,
        content_type: "space",
        content: "",
        lessonId: 15,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ច្បាប់នៃការសម្រេចចិត្ត",
        lessonId: 16,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដើម្បីធ្វើការសម្រេចចិត្ត អ្នកត្រូវប្រៀបធៀប P-value ជាមួយកម្រិតន័យសំខាន់ (α) ដែលអ្នកបានកំណត់។",
        lessonId: 16,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 16,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ប្រសិនបើ P-value ≤ α នោះអ្នកបដិសេធសម្មតិកម្ម null ។",
        lessonId: 16,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ប្រសិនបើ P-value > α នោះអ្នកមិនអាចបដិសេធសម្មតិកម្ម null បានទេ។",
        lessonId: 16,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការគណនាមធ្យមភាគ (Mean)",
        lessonId: 17,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដើម្បីគណនាមធ្យមភាគ (Mean) អ្នកត្រូវបូកតម្លៃទាំងអស់ក្នុងសំណុំទិន្នន័យហើយចែកនឹងចំនួនតម្លៃសរុប។ វាជារង្វាស់នៃទំនោរកណ្តាលដែលត្រូវបានប្រើប្រាស់ទូទៅបំផុត។",
        lessonId: 17,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 17,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ឧទាហរណ៍: (2 + 4 + 6 + 8) / 4 = 5",
        lessonId: 17,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "មធ្យមភាគងាយស្រួលគណនា ប៉ុន្តែវាអាចរងផលប៉ះពាល់ដោយតម្លៃមិនប្រក្រតី (outliers)។",
        lessonId: 17,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបរកឌីយ៉ង់",
        lessonId: 18,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំបូងអ្នកត្រូវតម្រៀបទិន្នន័យពីតូចទៅធំ។ បន្ទាប់មក រកតម្លៃដែលស្ថិតនៅចំកណ្តាល។ ប្រសិនបើទិន្នន័យមានចំនួនគូ ឌីយ៉ង់គឺជាមធ្យមភាគនៃតម្លៃកណ្តាលពីរ។",
        lessonId: 18,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 18,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ឧទាហរណ៍៖ សំណុំទិន្នន័យ (1, 3, 5, 8, 9) ឌីយ៉ង់គឺ 5។",
        lessonId: 18,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "ឌីយ៉ង់មិនរងផលប៉ះពាល់ដោយតម្លៃមិនប្រក្រតី ដូច្នេះវាល្អសម្រាប់ទិន្នន័យមិនស្មើគ្នា។",
        lessonId: 18,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់មូលដ្ឋាន",
        lessonId: 19,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "មូលដ្ឋាន (Mode) គឺជាតម្លៃដែលកើតឡើងញឹកញាប់បំផុត។ វាអាចប្រើសម្រាប់ទាំងទិន្នន័យគុណភាពនិងបរិមាណ។",
        lessonId: 19,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 19,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ឧទាហរណ៍៖ សំណុំទិន្នន័យ (1, 2, 2, 3, 4) មូលដ្ឋានគឺ 2។",
        lessonId: 19,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "អ្នកអាចមានមូលដ្ឋានច្រើនជាងមួយ ប្រសិនបើតម្លៃពីរឬច្រើនមានភាពញឹកញាប់ដូចគ្នា។",
        lessonId: 19,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ពេលណាត្រូវប្រើមធ្យមភាគ ឌីយ៉ង់ ឬមូលដ្ឋាន",
        lessonId: 20,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការជ្រើសរើសរង្វាស់កណ្តាលត្រឹមត្រូវអាស្រ័យលើប្រភេទទិន្នន័យនិងការចែកចាយរបស់វា។",
        lessonId: 20,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "មធ្យមភាគ៖ ល្អបំផុតសម្រាប់ទិន្នន័យបរិមាណដែលមានការចែកចាយធម្មតា។",
        lessonId: 20,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ឌីយ៉ង់៖ ល្អបំផុតសម្រាប់ទិន្នន័យដែលមានតម្លៃមិនប្រក្រតី។",
        lessonId: 20,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "មូលដ្ឋាន៖ ល្អបំផុតសម្រាប់ទិន្នន័យគុណភាពឬប្រភេទ។",
        lessonId: 20,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលបំណងនៃ T-Test",
        lessonId: 21,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "T-test ត្រូវបានប្រើដើម្បីប្រៀបធៀបមធ្យមភាគនៃសំណាកពីរដែលទាក់ទងគ្នា។ គោលបំណងគឺដើម្បីកំណត់ថាតើភាពខុសគ្នាគឺដោយសារកំហុសនៃការជ្រើសរើសសំណាក ឬដោយសារមូលហេតុពិតប្រាកដ។",
        lessonId: 21,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 21,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ប្រើដើម្បីប្រៀបធៀបមធ្យមភាគនៃក្រុមពីរ។",
        lessonId: 21,
    },
    {
        order_number: 5,
        content_type: "space",
        content: "",
        lessonId: 21,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ប្រភេទនៃ T-Test",
        lessonId: 22,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "មានបីប្រភេទនៃ T-test ដែលត្រូវប្រើអាស្រ័យលើលក្ខណៈនៃការស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 22,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 22,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "Independent Samples T-test: ប្រៀបធៀបក្រុមពីរដែលមិនពាក់ព័ន្ធគ្នា។",
        lessonId: 22,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "Paired Samples T-test: ប្រៀបធៀបទិន្នន័យពីក្រុមដូចគ្នាមុននិងក្រោយ។",
        lessonId: 22,
    },
    {
        order_number: 6,
        content_type: "list",
        content: "One-Sample T-test: ប្រៀបធៀបមធ្យមភាគសំណាកទៅនឹងមធ្យមភាគប្រជាជនដែលស្គាល់។",
        lessonId: 22,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "លក្ខខណ្ឌតម្រូវសម្រាប់ការប្រើ T-Test",
        lessonId: 23,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "ទិន្នន័យដែលបានវាស់វែងជាខ្នាតបន្ត (continuous scale) ។",
        lessonId: 23,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "ការបែងចែកទិន្នន័យមានលក្ខណៈធម្មតា (normal distribution) ។",
        lessonId: 23,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 23,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "ការបំពេញលក្ខខណ្ឌតម្រូវទាំងនេះធានានូវលទ្ធផលត្រឹមត្រូវនិងមានសុពលភាព។",
        lessonId: 23,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបកស្រាយលទ្ធផល T-Test",
        lessonId: 24,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ប្រសិនបើ P-value នៃ T-test តូចជាង 0.05 នោះមានភាពខុសគ្នាយ៉ាងសំខាន់រវាងមធ្យមភាគទាំងពីរ។",
        lessonId: 24,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 24,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "P-value < 0.05: បដិសេធសម្មតិកម្ម null។",
        lessonId: 24,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "P-value > 0.05: មិនអាចបដិសេធសម្មតិកម្ម null បានទេ។",
        lessonId: 24,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលដ្ឋានគ្រឹះនៃ ANOVA",
        lessonId: 25,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ANOVA ត្រូវបានប្រើដើម្បីប្រៀបធៀបមធ្យមភាគនៃក្រុមច្រើនជាងពីរ។ វាជួយអ្នកកំណត់ថាតើមានភាពខុសគ្នាជាសំខាន់រវាងមធ្យមភាគក្រុមណាមួយឬអត់។",
        lessonId: 25,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 25,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 25,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វាត្រូវបានគេប្រើជាញឹកញាប់ក្នុងការសិក្សាដែលប្រៀបធៀបក្រុមព្យាបាលជាច្រើន។",
        lessonId: 25,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ប្រភេទនៃ ANOVA",
        lessonId: 26,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "One-way ANOVA: មានអថេរឯករាជ្យមួយ។",
        lessonId: 26,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "Two-way ANOVA: មានអថេរឯករាជ្យពីរ។",
        lessonId: 26,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 26,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "ការជ្រើសរើសប្រភេទអាស្រ័យលើចំនួនអថេរឯករាជ្យក្នុងការស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 26,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "លក្ខខណ្ឌតម្រូវសម្រាប់ការប្រើ ANOVA",
        lessonId: 27,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "ទិន្នន័យដែលបានវាស់វែងជាខ្នាតបន្ត។",
        lessonId: 27,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "ការបែងចែកធម្មតានៃសំណល់។",
        lessonId: 27,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ភាពស្មើគ្នានៃវ៉ារ្យ៉ង់ក្នុងចំណោមក្រុម។",
        lessonId: 27,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបកស្រាយលទ្ធផល ANOVA",
        lessonId: 28,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ប្រសិនបើ P-value នៃ ANOVA តូចជាង 0.05 នោះមានភាពខុសគ្នាយ៉ាងសំខាន់រវាងមធ្យមភាគមួយចំនួននៅក្នុងក្រុម។",
        lessonId: 28,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 28,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "P-value < 0.05: បដិសេធសម្មតិកម្ម null។",
        lessonId: 28,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "P-value > 0.05: មិនមានភាពខុសគ្នាជាសំខាន់ទេ។",
        lessonId: 28,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្កើតម៉ូដែល Regression",
        lessonId: 29,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ម៉ូដែល Simple Linear Regression មានទម្រង់ជា Y = a + bX ដែល a គឺជាចំណុចកាត់ y និង b គឺជាជម្រាល។ វាជួយអ្នកព្យាករណ៍តម្លៃរបស់អថេរមួយដោយផ្អែកលើអថេរមួយទៀត។",
        lessonId: 29,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=11",
        lessonId: 29,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 29,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "Y គឺជាអថេរអាស្រ័យ។",
        lessonId: 29,
    },
    {
        order_number: 6,
        content_type: "list",
        content: "X គឺជាអថេរឯករាជ្យ។",
        lessonId: 29,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបកស្រាយជម្រាល (Slope)",
        lessonId: 30,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍ជួយអ្នកឱ្យយល់ពីការស្រាវជ្រាវដែលមានស្រាប់ និងកំណត់ពីចំណុចខ្វះខាត។ វាជារបាយការណ៍ដែលបានរៀបចំជាប្រព័ន្ធនៃព័ត៌មានដែលទាក់ទងនឹងប្រធានបទរបស់អ្នក។",
        lessonId: 30,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 30,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយអ្នកកំណត់សំណួរស្រាវជ្រាវផ្ទាល់ខ្លួនរបស់អ្នក។",
        lessonId: 30,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វាជៀសវាងការចម្លងការងារពីអ្នកដទៃ។",
        lessonId: 30,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការវាយតម្លៃម៉ូដែល",
        lessonId: 31,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការវាយតម្លៃម៉ូដែលរួមមានការមើលទៅលើ R-squared ដែលវាស់ពីភាគរយនៃបំរែបំរួលដែលត្រូវបានពន្យល់ដោយម៉ូដែល។ តម្លៃ R-squared កាន់តែខ្ពស់ ម៉ូដែលកាន់តែល្អ។",
        lessonId: 31,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=12",
        lessonId: 31,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 31,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "R-squared អាចមានចន្លោះពី 0 ដល់ 1។",
        lessonId: 31,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការព្យាករណ៍ជាមួយម៉ូដែល",
        lessonId: 32,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "នៅពេលដែលម៉ូដែលត្រូវបានបង្កើត អ្នកអាចប្រើវាដើម្បីព្យាករណ៍តម្លៃរបស់អថេរអាស្រ័យ។ វាមានប្រយោជន៍សម្រាប់ការសម្រេចចិត្តដោយផ្អែកលើទិន្នន័យ។",
        lessonId: 32,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 32,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ត្រូវប្រាកដថាអថេរឯករាជ្យស្ថិតនៅក្នុងជួរទិន្នន័យដើមរបស់អ្នក។",
        lessonId: 32,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលដ្ឋានគ្រឹះនៃ Multiple Regression",
        lessonId: 33,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Multiple Regression ត្រូវបានប្រើដើម្បីសិក្សាពីឥទ្ធិពលនៃអថេរឯករាជ្យច្រើនលើអថេរអាស្រ័យមួយ។ វាផ្តល់នូវការវិភាគដែលទូលំទូលាយជាង Simple Regression។",
        lessonId: 33,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 33,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយពន្យល់ពីទំនាក់ទំនងស្មុគស្មាញរវាងអថេរ។",
        lessonId: 33,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្កើតម៉ូដែល",
        lessonId: 34,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ម៉ូដែល Multiple Regression មានទម្រង់ជា Y = a + b₁X₁ + b₂X₂ + ...។ វាអនុញ្ញាតឱ្យអ្នកបញ្ចូលអថេរជាច្រើនដើម្បីបង្កើនភាពត្រឹមត្រូវនៃការព្យាករណ៍។",
        lessonId: 34,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 34,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "X₁, X₂, ... គឺជាអថេរឯករាជ្យ។",
        lessonId: 34,
    },
    {
        order_number: 5,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=13",
        lessonId: 34,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបកស្រាយមេគុណ",
        lessonId: 35,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "មេគុណ (b) តំណាងឱ្យឥទ្ធិពលរបស់អថេរឯករាជ្យមួយទៅលើអថេរអាស្រ័យដោយរក្សាអថេរផ្សេងទៀតឱ្យថេរ។ វាជួយឱ្យអ្នកយល់ពីឥទ្ធិពលរបស់អថេរនីមួយៗ។",
        lessonId: 35,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 35,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "មេគុណវិជ្ជមានមានន័យថាទំនាក់ទំនងវិជ្ជមាន។",
        lessonId: 35,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "មេគុណអវិជ្ជមានមានន័យថាទំនាក់ទំនងអវិជ្ជមាន។",
        lessonId: 35,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការវាយតម្លៃម៉ូដែល",
        lessonId: 36,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការវាយតម្លៃម៉ូដែល Multiple Regression រួមមានការប្រើ Adjusted R-squared និងការធ្វើតេស្ត F-test។ ទាំងនេះជួយកំណត់ពីភាពសមស្របរបស់ម៉ូដែល។",
        lessonId: 36,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 36,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "Adjusted R-squared ពិន័យលើការបន្ថែមអថេរច្រើនពេក។",
        lessonId: 36,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "F-test វាយតម្លៃភាពសំខាន់នៃម៉ូដែលទាំងមូល។",
        lessonId: 36,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "R-squared និង Adjusted R-squared",
        lessonId: 37,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "R-squared វាស់ភាគរយនៃបំរែបំរួលដែលត្រូវបានពន្យល់ដោយម៉ូដែល ហើយ Adjusted R-squared ត្រូវបានកែតម្រូវសម្រាប់ចំនួនអថេរ។ វាជួយវាយតម្លៃភាពសមស្របរបស់ម៉ូដែល។",
        lessonId: 37,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=14",
        lessonId: 37,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 37,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "R-squared តែងតែកើនឡើងនៅពេលអ្នកបន្ថែមអថេរ។",
        lessonId: 37,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការធ្វើតេស្តភាពសំខាន់",
        lessonId: 38,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការធ្វើតេស្ត t-test ត្រូវបានប្រើដើម្បីកំណត់ថាតើមេគុណនីមួយៗមានភាពសំខាន់ឬអត់។ P-value នៃ t-test ជួយធ្វើការសម្រេចចិត្ត។",
        lessonId: 38,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 38,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ប្រសិនបើ P < 0.05 នោះមេគុណមានភាពសំខាន់។",
        lessonId: 38,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "លក្ខខណ្ឌតម្រូវនៃ Regression",
        lessonId: 39,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដើម្បីឱ្យលទ្ធផល Regression មានសុពលភាព លក្ខខណ្ឌតម្រូវមួយចំនួនត្រូវតែបំពេញ។",
        lessonId: 39,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 39,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "លីនេអ៊ែរភាពរវាងអថេរ។",
        lessonId: 39,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ភាពធម្មតានៃកំហុស។",
        lessonId: 39,
    },
    {
        order_number: 6,
        content_type: "list",
        content: "ភាពស្មើគ្នានៃវ៉ារ្យ៉ង់ (homoscedasticity)។",
        lessonId: 39,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ residual plots",
        lessonId: 40,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Residual plots ជួយយើងពិនិត្យមើលថាតើលក្ខខណ្ឌតម្រូវនៃ Regression ត្រូវបានបំពេញឬអត់។",
        lessonId: 40,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=15",
        lessonId: 40,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 40,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ប្រសិនបើចំណុចត្រូវបានរាយប៉ាយដោយចៃដន្យ នោះលក្ខខណ្ឌត្រូវបានបំពេញ។",
        lessonId: 40,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការជ្រើសរើសសំណាកតាម Simple Random",
        lessonId: 41,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Simple Random Sampling គឺជាវិធីសាស្ត្រដែលសមាជិកនីមួយៗនៃប្រជាជនមានឱកាសស្មើៗគ្នាក្នុងការត្រូវបានជ្រើសរើស។ វាជាវិធីសាស្ត្រជ្រើសរើសសំណាកគ្មានភាពលម្អៀង។",
        lessonId: 41,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 41,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាទាមទារបញ្ជីពេញលេញនៃប្រជាជន។",
        lessonId: 41,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបអនុវត្ត",
        lessonId: 42,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកអាចអនុវត្តវាដោយប្រើកម្មវិធីបង្កើតលេខចៃដន្យ ឬដោយការចាប់ឆ្នោត។ វាជាវិធីសាស្ត្រងាយស្រួលនិងអាចទុកចិត្តបាន។",
        lessonId: 42,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=16",
        lessonId: 42,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 42,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ជ្រើសរើសសំណាកដោយចៃដន្យ។",
        lessonId: 42,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គុណសម្បត្តិ និងគុណវិបត្តិ",
        lessonId: 43,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "គុណសម្បត្តិ: គ្មានភាពលម្អៀងនិងងាយស្រួលអនុវត្ត។",
        lessonId: 43,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "គុណវិបត្តិ: អាចមានការលំបាកក្នុងការទទួលបានបញ្ជីប្រជាជនពេញលេញ។",
        lessonId: 43,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 43,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "វាជាវិធីសាស្ត្រជ្រើសរើសសំណាកដ៏ល្អបំផុតនៅពេលដែលអាចអនុវត្តបាន។",
        lessonId: 43,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការអនុវត្តជាក់ស្តែង",
        lessonId: 44,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "វាត្រូវបានប្រើប្រាស់យ៉ាងទូលំទូលាយក្នុងការស្ទង់មតិដែលមានលក្ខណៈតំណាង។ វាជាវិធីសាស្ត្រស្តង់ដារមួយសម្រាប់ការស្រាវជ្រាវវិទ្យាសាស្ត្រ។",
        lessonId: 44,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 44,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=17",
        lessonId: 44,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលការណ៍នៃ Systematic Sampling",
        lessonId: 45,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Systematic Sampling ជ្រើសរើសសមាជិកដោយប្រើចន្លោះពេលទៀងទាត់ពីបញ្ជីប្រជាជន។ វាលឿននិងមានប្រសិទ្ធភាពជាងវិធីសាស្ត្រ Simple Random។",
        lessonId: 45,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 45,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាអាចប្រើបាននៅពេលដែលប្រជាជនត្រូវបានរៀបចំជាលំដាប់។",
        lessonId: 45,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបអនុវត្ត",
        lessonId: 46,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកកំណត់ចន្លោះពេលជ្រើសរើស (k) ហើយជ្រើសរើសសមាជិកទីមួយដោយចៃដន្យ។ បន្ទាប់មកជ្រើសរើសសមាជិកបន្ទាប់រៀងរាល់ k។",
        lessonId: 46,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=18",
        lessonId: 46,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 46,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ឧទាហរណ៍: ជ្រើសរើសមនុស្សទី 5, ទី 10, ទី 15, ...។",
        lessonId: 46,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គុណសម្បត្តិ និងគុណវិបត្តិ",
        lessonId: 47,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "គុណសម្បត្តិ: លឿននិងងាយស្រួលអនុវត្ត។",
        lessonId: 47,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "គុណវិបត្តិ: អាចមានភាពលម្អៀងប្រសិនបើមានលំនាំនៅក្នុងបញ្ជី។",
        lessonId: 47,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 47,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "វាចាំបាច់ត្រូវប្រុងប្រយ័ត្នចំពោះលំនាំនៅក្នុងបញ្ជីរបស់អ្នក។",
        lessonId: 47,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការអនុវត្តជាក់ស្តែង",
        lessonId: 48,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "វាត្រូវបានប្រើសម្រាប់ការស្ទង់មតិលើកម្រិតផលិតកម្មឬការត្រួតពិនិត្យគុណភាព។ វាមានប្រយោជន៍នៅពេលដែលបញ្ជីមានលក្ខណៈរៀបចំ។",
        lessonId: 48,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 48,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=19",
        lessonId: 48,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលការណ៍នៃ Stratified Sampling",
        lessonId: 49,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Stratified Sampling បែងចែកប្រជាជនជាក្រុមរង (strata) ហើយជ្រើសរើសសំណាកពីក្រុមនីមួយៗ។ វាធានាថាក្រុមរងសំខាន់ៗត្រូវបានតំណាង។",
        lessonId: 49,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 49,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាត្រូវបានប្រើដើម្បីដោះស្រាយបញ្ហាប្រជាជនដែលមានភាពខុសគ្នា។",
        lessonId: 49,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបអនុវត្ត",
        lessonId: 50,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកបែងចែកប្រជាជនទៅជាក្រុមរងដែលមិនត្រួតស៊ីគ្នា ហើយបន្ទាប់មកជ្រើសរើសសំណាកដោយចៃដន្យពីក្រុមនីមួយៗ។",
        lessonId: 50,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=20",
        lessonId: 50,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 50,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វាជួយឱ្យសំណាកមានលក្ខណៈតំណាងបានល្អ។",
        lessonId: 50,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គុណសម្បត្តិ និងគុណវិបត្តិ",
        lessonId: 51,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "គុណសម្បត្តិ: ធានាថាក្រុមរងសំខាន់ៗត្រូវបានតំណាង។",
        lessonId: 51,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "គុណវិបត្តិ: អាចមានការលំបាកក្នុងការកំណត់ក្រុមរង។",
        lessonId: 51,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 51,
    },
    {
        order_number: 5,
        content_type: "text",
        content: "វាមានប្រសិទ្ធភាពតែនៅពេលដែលក្រុមរងត្រូវបានកំណត់ច្បាស់លាស់។",
        lessonId: 51,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការអនុវត្តជាក់ស្តែង",
        lessonId: 52,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "វាត្រូវបានប្រើក្នុងការស្រាវជ្រាវទីផ្សារ ឬការស្ទង់មតិសាធារណៈ។ វាមានប្រយោជន៍នៅពេលដែលអ្នកចង់ប្រៀបធៀបក្រុមរងផ្សេងៗ។",
        lessonId: 52,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 52,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=21",
        lessonId: 52,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលការណ៍នៃ Cluster Sampling",
        lessonId: 53,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Cluster Sampling ជ្រើសរើសក្រុមទាំងមូល (clusters) ជាជាងបុគ្គល ហើយធ្វើការស្រាវជ្រាវលើពួកគេទាំងអស់។ នេះជួយសន្សំសំចៃពេលវេលានិងថវិកា។",
        lessonId: 53,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 53,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាមានប្រយោជន៍នៅពេលដែលប្រជាជនស្ថិតនៅជាក្រុមធម្មជាតិ។",
        lessonId: 53,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "របៀបអនុវត្ត",
        lessonId: 54,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំបូងអ្នកបែងចែកប្រជាជនជាក្រុម ឬចង្កោម ហើយបន្ទាប់មកជ្រើសរើសចង្កោមមួយចំនួនដោយចៃដន្យ។ បន្ទាប់មកសិក្សាពីសមាជិកទាំងអស់នៅក្នុងចង្កោមដែលបានជ្រើសរើស។",
        lessonId: 54,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=22",
        lessonId: 54,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 54,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វាត្រូវបានគេប្រើជាញឹកញាប់សម្រាប់ការស្ទង់មតិលើតំបន់ភូមិសាស្ត្រធំៗ។",
        lessonId: 54,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរចនាការសង្កេត",
        lessonId: 55,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការរចនាការសង្កេតអនុញ្ញាតឱ្យអ្នកសិក្សាពីអាកប្បកិរិយារបស់មនុស្សនៅក្នុងបរិយាកាសធម្មជាតិ។ វាផ្តល់នូវទិន្នន័យជាក់ស្តែងដែលមិនប៉ះពាល់ដោយការសម្ភាសន៍។",
        lessonId: 55,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 55,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វារួមមានការសង្កេតអ្នកចូលរួមនិងមិនមែនអ្នកចូលរួម។",
        lessonId: 55,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរចនាការសិក្សាករណី",
        lessonId: 56,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការរចនាការសិក្សាករណីត្រូវបានប្រើដើម្បីសិក្សាពីបាតុភូតតែមួយក្នុងលក្ខណៈស៊ីជម្រៅ។ វាផ្តល់នូវការយល់ដឹងដ៏កម្រនិងទូលំទូលាយ។",
        lessonId: 56,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 56,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាផ្តោតលើបុគ្គល ក្រុម ឬព្រឹត្តិការណ៍តែមួយ។",
        lessonId: 56,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរបញ្ហាស្រាវជ្រាវ",
        lessonId: 57,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "បញ្ហាស្រាវជ្រាវគឺជាអ្វីដែលការស្រាវជ្រាវរបស់អ្នកចង់ដោះស្រាយ។ វាត្រូវតែច្បាស់លាស់និងជាក់លាក់ដើម្បីដឹកនាំការស្រាវជ្រាវ។",
        lessonId: 57,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 57,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែមានលក្ខណៈទាក់ទាញនិងអាចដោះស្រាយបាន។",
        lessonId: 57,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលហេតុនៃការពិនិត្យអក្សរសិល្ប៍",
        lessonId: 58,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍ជួយអ្នកឱ្យយល់ពីការស្រាវជ្រាវដែលមានស្រាប់ និងកំណត់ពីចំណុចខ្វះខាត។ វាជារបាយការណ៍ដែលបានរៀបចំជាប្រព័ន្ធនៃព័ត៌មានដែលទាក់ទងនឹងប្រធានបទរបស់អ្នក។",
        lessonId: 58,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 58,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជៀសវាងការចម្លងការងារពីអ្នកដទៃ។",
        lessonId: 58,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ឧបករណ៍ប្រមូលទិន្នន័យ",
        lessonId: 59,
    },
    {
        order_number: 2,
        content_type: "list",
        content: "មគ្គុទ្ទេសក៍សម្ភាសន៍: ប្រើសំណួរដែលមានលក្ខណៈបើកចំហ។",
        lessonId: 59,
    },
    {
        order_number: 3,
        content_type: "list",
        content: "ឧបករណ៍ថតសំឡេង: សម្រាប់ការថតការសម្ភាសន៍។",
        lessonId: 59,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "កំណត់ហេតុប្រចាំថ្ងៃ: សម្រាប់ការកត់ត្រាលម្អិតនៃការសង្កេត។",
        lessonId: 59,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការចម្លងតាម (Transcription)",
        lessonId: 60,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការចម្លងតាមគឺជាដំណើរការនៃការបំប្លែងការសម្ភាសន៍ដែលបានថតជាទម្រង់អត្ថបទ។ វាជាជំហានចាំបាច់មុនពេលវិភាគទិន្នន័យគុណភាព។",
        lessonId: 60,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 60,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ត្រូវប្រាកដថាការចម្លងតាមមានភាពត្រឹមត្រូវ។",
        lessonId: 60,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការគ្រប់គ្រងទិន្នន័យ",
        lessonId: 61,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការគ្រប់គ្រងទិន្នន័យល្អគឺមានសារៈសំខាន់សម្រាប់ការវិភាគត្រឹមត្រូវ។ អ្នកត្រូវតែរៀបចំនិងរក្សាទុកទិន្នន័យរបស់អ្នកដោយប្រុងប្រយ័ត្ន។",
        lessonId: 61,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 61,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការរៀបចំទិន្នន័យសម្រាប់ការវិភាគ។",
        lessonId: 61,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរចនា Explanatory",
        lessonId: 62,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការរចនា Explanatory ចាប់ផ្តើមដោយការស្រាវជ្រាវបរិមាណ ហើយបន្ទាប់មកប្រើការស្រាវជ្រាវគុណភាពដើម្បីពន្យល់លទ្ធផល។ វាជួយឱ្យអ្នកយល់ពីមូលហេតុ។",
        lessonId: 62,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 62,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=23",
        lessonId: 62,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរចនា Exploratory",
        lessonId: 63,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការរចនា Exploratory ចាប់ផ្តើមដោយការស្រាវជ្រាវគុណភាព ហើយបន្ទាប់មកប្រើការស្រាវជ្រាវបរិមាណដើម្បីសាកល្បងលទ្ធផល។ វាមានប្រយោជន៍នៅពេលដែលអ្នកមានការយល់ដឹងតិចតួចអំពីប្រធានបទ។",
        lessonId: 63,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 63,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាមានប្រយោជន៍សម្រាប់បង្កើតសម្មតិកម្មថ្មី។",
        lessonId: 63,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរចនា Triangulation",
        lessonId: 64,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការរចនា Triangulation ប្រើវិធីសាស្ត្រទាំងពីរក្នុងពេលដំណាលគ្នាដើម្បីទទួលបានលទ្ធផលដែលរឹងមាំ។ វាជួយផ្ទៀងផ្ទាត់លទ្ធផលពីវិធីសាស្ត្រមួយទៅវិធីសាស្ត្រមួយទៀត។",
        lessonId: 64,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 64,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយកាត់បន្ថយភាពលម្អៀង។",
        lessonId: 64,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការជ្រើសរើសការរចនា",
        lessonId: 65,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការជ្រើសរើសការរចនាដែលត្រឹមត្រូវអាស្រ័យលើសំណួរស្រាវជ្រាវនិងគោលបំណងរបស់អ្នក។",
        lessonId: 65,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 65,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "Exploratory: ប្រើពេលដែលអ្នកចង់បង្កើតទ្រឹស្តី។",
        lessonId: 65,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "Explanatory: ប្រើពេលដែលអ្នកចង់សាកល្បងទ្រឹស្តី។",
        lessonId: 65,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រមូលទិន្នន័យបរិមាណ",
        lessonId: 66,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការប្រមូលទិន្នន័យបរិមាណត្រូវបានធ្វើដោយប្រើកម្រងសំណួរ ការស្ទង់មតិអនឡាញ។ វាមានប្រសិទ្ធភាពសម្រាប់ការប្រមូលទិន្នន័យពីមនុស្សមួយចំនួនធំ។",
        lessonId: 66,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 66,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=24",
        lessonId: 66,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រមូលទិន្នន័យគុណភាព",
        lessonId: 67,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការប្រមូលទិន្នន័យគុណភាពត្រូវបានធ្វើដោយប្រើការសម្ភាសន៍ ឬការសង្កេត។ វាផ្តល់នូវការយល់ដឹងស៊ីជម្រៅពីប្រធានបទ។",
        lessonId: 67,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 67,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយយល់ពីបទពិសោធន៍ផ្ទាល់ខ្លួន។",
        lessonId: 67,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបញ្ចូលទិន្នន័យ",
        lessonId: 68,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការបញ្ចូលទិន្នន័យគឺជាដំណើរការនៃការបញ្ចូលទិន្នន័យទៅក្នុងកម្មវិធីវិភាគ។ វាចាំបាច់ដើម្បីរៀបចំទិន្នន័យមុនពេលវិភាគ។",
        lessonId: 68,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=25",
        lessonId: 68,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 68,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ត្រូវពិនិត្យមើលកំហុសក្នុងការបញ្ចូលទិន្នន័យ។",
        lessonId: 68,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការគ្រប់គ្រងទិន្នន័យ",
        lessonId: 69,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការគ្រប់គ្រងទិន្នន័យល្អគឺមានសារៈសំខាន់សម្រាប់ការវិភាគត្រឹមត្រូវ។ អ្នកត្រូវតែរៀបចំនិងរក្សាទុកទិន្នន័យរបស់អ្នកដោយប្រុងប្រយ័ត្ន។",
        lessonId: 69,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 69,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការរៀបចំទិន្នន័យសម្រាប់ការវិភាគ។",
        lessonId: 69,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរបញ្ហាស្រាវជ្រាវ",
        lessonId: 70,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "បញ្ហាស្រាវជ្រាវគឺជាអ្វីដែលការស្រាវជ្រាវរបស់អ្នកចង់ដោះស្រាយ។ វាត្រូវតែច្បាស់លាស់និងជាក់លាក់ដើម្បីដឹកនាំការស្រាវជ្រាវ។",
        lessonId: 70,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 70,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែមានលក្ខណៈទាក់ទាញនិងអាចដោះស្រាយបាន។",
        lessonId: 70,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរសេចក្តីថ្លែងការណ៍",
        lessonId: 71,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សេចក្តីថ្លែងការណ៍បញ្ហាគួរតែច្បាស់លាស់ ជាក់លាក់ និងគួរឱ្យចាប់អារម្មណ៍។ វាជាចំណុចកណ្តាលនៃសំណើរស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 71,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 71,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=26",
        lessonId: 71,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "វាគួរតែបញ្ជាក់ពីគម្លាតនៅក្នុងចំណេះដឹង។",
        lessonId: 71,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្កើតសំណួរស្រាវជ្រាវ",
        lessonId: 72,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សំណួរស្រាវជ្រាវត្រូវតែអាចវាស់វែងបាន និងអាចឆ្លើយបានតាមរយៈការស្រាវជ្រាវ។ វាជួយផ្តោតការស្រាវជ្រាវរបស់អ្នកទៅលើគោលបំណងច្បាស់លាស់។",
        lessonId: 72,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 72,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែមានលក្ខណៈជាក់លាក់និងអាចវាស់វែងបាន។",
        lessonId: 72,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលបំណងនៃការស្រាវជ្រាវ",
        lessonId: 73,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "គោលបំណងកំណត់ពីអ្វីដែលអ្នកចង់សម្រេចបានតាមរយៈការស្រាវជ្រាវរបស់អ្នក។ វាគួរតែមានលក្ខណៈជាក់លាក់និងអាចវាស់វែងបាន។",
        lessonId: 73,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 73,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយដឹកនាំការស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 73,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលហេតុនៃការពិនិត្យអក្សរសិល្ប៍",
        lessonId: 74,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍ជួយអ្នកឱ្យយល់ពីការស្រាវជ្រាវដែលមានស្រាប់ និងកំណត់ពីចំណុចខ្វះខាត។ វាជាមូលដ្ឋានគ្រឹះសម្រាប់ការស្រាវជ្រាវថ្មី។",
        lessonId: 74,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 74,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=27",
        lessonId: 74,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ដំណើរការនៃការពិនិត្យ",
        lessonId: 75,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំណើរការនេះរួមមានការស្វែងរក អាន វាយតម្លៃ និងសង្ខេបអត្ថបទស្រាវជ្រាវដែលពាក់ព័ន្ធ។",
        lessonId: 75,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 75,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយអ្នករៀបចំចំណេះដឹងពីមុន។",
        lessonId: 75,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរៀបចំរចនាសម្ព័ន្ធ",
        lessonId: 76,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍គួរតែត្រូវបានរៀបចំតាមប្រធានបទឬកាលបរិច្ឆេទ។",
        lessonId: 76,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 76,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "រចនាសម្ព័ន្ធល្អជួយឱ្យអ្នកអានយល់ពីប្រធានបទរបស់អ្នកបានយ៉ាងងាយស្រួល។",
        lessonId: 76,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរផ្នែកពិនិត្យ",
        lessonId: 77,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកគួរតែសង្ខេបនិងវាយតម្លៃការរកឃើញសំខាន់ៗដោយមិនគ្រាន់តែរាយបញ្ជី។ វាបង្ហាញពីការយល់ដឹងស៊ីជម្រៅរបស់អ្នក។",
        lessonId: 77,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=28",
        lessonId: 77,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 77,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ត្រូវប្រាកដថាអ្នកកំណត់គម្លាតនៅក្នុងអក្សរសិល្ប៍។",
        lessonId: 77,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរបញ្ហាស្រាវជ្រាវ",
        lessonId: 78,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "បញ្ហាស្រាវជ្រាវគឺជាអ្វីដែលការស្រាវជ្រាវរបស់អ្នកចង់ដោះស្រាយ។ វាត្រូវតែច្បាស់លាស់និងជាក់លាក់ដើម្បីដឹកនាំការស្រាវជ្រាវ។",
        lessonId: 78,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 78,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែមានលក្ខណៈទាក់ទាញនិងអាចដោះស្រាយបាន។",
        lessonId: 78,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរសេចក្តីថ្លែងការណ៍",
        lessonId: 79,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សេចក្តីថ្លែងការណ៍បញ្ហាគួរតែច្បាស់លាស់ ជាក់លាក់ និងគួរឱ្យចាប់អារម្មណ៍។ វាជាចំណុចកណ្តាលនៃសំណើរស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 79,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 79,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែបញ្ជាក់ពីគម្លាតនៅក្នុងចំណេះដឹង។",
        lessonId: 79,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្កើតសំណួរស្រាវជ្រាវ",
        lessonId: 80,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សំណួរស្រាវជ្រាវត្រូវតែអាចវាស់វែងបាន និងអាចឆ្លើយបានតាមរយៈការស្រាវជ្រាវ។ វាជួយផ្តោតការស្រាវជ្រាវរបស់អ្នកទៅលើគោលបំណងច្បាស់លាស់។",
        lessonId: 80,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 80,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=29",
        lessonId: 80,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលបំណងនៃការស្រាវជ្រាវ",
        lessonId: 81,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "គោលបំណងកំណត់ពីអ្វីដែលអ្នកចង់សម្រេចបានតាមរយៈការស្រាវជ្រាវរបស់អ្នក។ វាគួរតែមានលក្ខណៈជាក់លាក់និងអាចវាស់វែងបាន។",
        lessonId: 81,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 81,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយដឹកនាំការស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 81,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលហេតុនៃការពិនិត្យអក្សរសិល្ប៍",
        lessonId: 82,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍ជួយអ្នកឱ្យយល់ពីការស្រាវជ្រាវដែលមានស្រាប់ និងកំណត់ពីចំណុចខ្វះខាត។ វាជាមូលដ្ឋានគ្រឹះសម្រាប់ការស្រាវជ្រាវថ្មី។",
        lessonId: 82,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 82,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=30",
        lessonId: 82,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ដំណើរការនៃការពិនិត្យ",
        lessonId: 83,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំណើរការនេះរួមមានការស្វែងរក អាន វាយតម្លៃ និងសង្ខេបអត្ថបទស្រាវជ្រាវដែលពាក់ព័ន្ធ។",
        lessonId: 83,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 83,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយអ្នករៀបចំចំណេះដឹងពីមុន។",
        lessonId: 83,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរៀបចំរចនាសម្ព័ន្ធ",
        lessonId: 84,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍គួរតែត្រូវបានរៀបចំតាមប្រធានបទឬកាលបរិច្ឆេទ។",
        lessonId: 84,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 84,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "រចនាសម្ព័ន្ធល្អជួយឱ្យអ្នកអានយល់ពីប្រធានបទរបស់អ្នកបានយ៉ាងងាយស្រួល។",
        lessonId: 84,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរផ្នែកពិនិត្យ",
        lessonId: 85,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកគួរតែសង្ខេបនិងវាយតម្លៃការរកឃើញសំខាន់ៗដោយមិនគ្រាន់តែរាយបញ្ជី។ វាបង្ហាញពីការយល់ដឹងស៊ីជម្រៅរបស់អ្នក។",
        lessonId: 85,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=31",
        lessonId: 85,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 85,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ត្រូវប្រាកដថាអ្នកកំណត់គម្លាតនៅក្នុងអក្សរសិល្ប៍។",
        lessonId: 85,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរបញ្ហាស្រាវជ្រាវ",
        lessonId: 86,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "បញ្ហាស្រាវជ្រាវគឺជាអ្វីដែលការស្រាវជ្រាវរបស់អ្នកចង់ដោះស្រាយ។ វាត្រូវតែច្បាស់លាស់និងជាក់លាក់ដើម្បីដឹកនាំការស្រាវជ្រាវ។",
        lessonId: 86,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 86,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែមានលក្ខណៈទាក់ទាញនិងអាចដោះស្រាយបាន។",
        lessonId: 86,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរសេចក្តីថ្លែងការណ៍",
        lessonId: 87,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សេចក្តីថ្លែងការណ៍បញ្ហាគួរតែច្បាស់លាស់ ជាក់លាក់ និងគួរឱ្យចាប់អារម្មណ៍។ វាជាចំណុចកណ្តាលនៃសំណើរស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 87,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 87,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែបញ្ជាក់ពីគម្លាតនៅក្នុងចំណេះដឹង។",
        lessonId: 87,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្កើតសំណួរស្រាវជ្រាវ",
        lessonId: 88,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សំណួរស្រាវជ្រាវត្រូវតែអាចវាស់វែងបាន និងអាចឆ្លើយបានតាមរយៈការស្រាវជ្រាវ។ វាជួយផ្តោតការស្រាវជ្រាវរបស់អ្នកទៅលើគោលបំណងច្បាស់លាស់។",
        lessonId: 88,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 88,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=32",
        lessonId: 88,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលបំណងនៃការស្រាវជ្រាវ",
        lessonId: 89,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "គោលបំណងកំណត់ពីអ្វីដែលអ្នកចង់សម្រេចបានតាមរយៈការស្រាវជ្រាវរបស់អ្នក។ វាគួរតែមានលក្ខណៈជាក់លាក់និងអាចវាស់វែងបាន។",
        lessonId: 89,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 89,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយដឹកនាំការស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 89,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលហេតុនៃការពិនិត្យអក្សរសិល្ប៍",
        lessonId: 90,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍ជួយអ្នកឱ្យយល់ពីការស្រាវជ្រាវដែលមានស្រាប់ និងកំណត់ពីចំណុចខ្វះខាត។ វាជាមូលដ្ឋានគ្រឹះសម្រាប់ការស្រាវជ្រាវថ្មី។",
        lessonId: 90,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 90,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=33",
        lessonId: 90,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ដំណើរការនៃការពិនិត្យ",
        lessonId: 91,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំណើរការនេះរួមមានការស្វែងរក អាន វាយតម្លៃ និងសង្ខេបអត្ថបទស្រាវជ្រាវដែលពាក់ព័ន្ធ។",
        lessonId: 91,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 91,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយអ្នករៀបចំចំណេះដឹងពីមុន។",
        lessonId: 91,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរៀបចំរចនាសម្ព័ន្ធ",
        lessonId: 92,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍គួរតែត្រូវបានរៀបចំតាមប្រធានបទឬកាលបរិច្ឆេទ។",
        lessonId: 92,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 92,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "រចនាសម្ព័ន្ធល្អជួយឱ្យអ្នកអានយល់ពីប្រធានបទរបស់អ្នកបានយ៉ាងងាយស្រួល។",
        lessonId: 92,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរផ្នែកពិនិត្យ",
        lessonId: 93,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកគួរតែសង្ខេបនិងវាយតម្លៃការរកឃើញសំខាន់ៗដោយមិនគ្រាន់តែរាយបញ្ជី។ វាបង្ហាញពីការយល់ដឹងស៊ីជម្រៅរបស់អ្នក។",
        lessonId: 93,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=34",
        lessonId: 93,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 93,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ត្រូវប្រាកដថាអ្នកកំណត់គម្លាតនៅក្នុងអក្សរសិល្ប៍។",
        lessonId: 93,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរបញ្ហាស្រាវជ្រាវ",
        lessonId: 94,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "បញ្ហាស្រាវជ្រាវគឺជាអ្វីដែលការស្រាវជ្រាវរបស់អ្នកចង់ដោះស្រាយ។ វាត្រូវតែច្បាស់លាស់និងជាក់លាក់ដើម្បីដឹកនាំការស្រាវជ្រាវ។",
        lessonId: 94,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 94,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែមានលក្ខណៈទាក់ទាញនិងអាចដោះស្រាយបាន។",
        lessonId: 94,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរសេចក្តីថ្លែងការណ៍",
        lessonId: 95,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សេចក្តីថ្លែងការណ៍បញ្ហាគួរតែច្បាស់លាស់ ជាក់លាក់ និងគួរឱ្យចាប់អារម្មណ៍។ វាជាចំណុចកណ្តាលនៃសំណើរស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 95,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 95,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាគួរតែបញ្ជាក់ពីគម្លាតនៅក្នុងចំណេះដឹង។",
        lessonId: 95,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្កើតសំណួរស្រាវជ្រាវ",
        lessonId: 96,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "សំណួរស្រាវជ្រាវត្រូវតែអាចវាស់វែងបាន និងអាចឆ្លើយបានតាមរយៈការស្រាវជ្រាវ។ វាជួយផ្តោតការស្រាវជ្រាវរបស់អ្នកទៅលើគោលបំណងច្បាស់លាស់។",
        lessonId: 96,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 96,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=35",
        lessonId: 96,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "គោលបំណងនៃការស្រាវជ្រាវ",
        lessonId: 97,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "គោលបំណងកំណត់ពីអ្វីដែលអ្នកចង់សម្រេចបានតាមរយៈការស្រាវជ្រាវរបស់អ្នក។ វាគួរតែមានលក្ខណៈជាក់លាក់និងអាចវាស់វែងបាន។",
        lessonId: 97,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 97,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយដឹកនាំការស្រាវជ្រាវរបស់អ្នក។",
        lessonId: 97,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "មូលហេតុនៃការពិនិត្យអក្សរសិល្ប៍",
        lessonId: 98,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍ជួយអ្នកឱ្យយល់ពីការស្រាវជ្រាវដែលមានស្រាប់ និងកំណត់ពីចំណុចខ្វះខាត។ វាជាមូលដ្ឋានគ្រឹះសម្រាប់ការស្រាវជ្រាវថ្មី។",
        lessonId: 98,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 98,
    },
    {
        order_number: 4,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=36",
        lessonId: 98,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ដំណើរការនៃការពិនិត្យ",
        lessonId: 99,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ដំណើរការនេះរួមមានការស្វែងរក អាន វាយតម្លៃ និងសង្ខេបអត្ថបទស្រាវជ្រាវដែលពាក់ព័ន្ធ។",
        lessonId: 99,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 99,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "វាជួយអ្នករៀបចំចំណេះដឹងពីមុន។",
        lessonId: 99,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការរៀបចំរចនាសម្ព័ន្ធ",
        lessonId: 100,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការពិនិត្យអក្សរសិល្ប៍គួរតែត្រូវបានរៀបចំតាមប្រធានបទឬកាលបរិច្ឆេទ។",
        lessonId: 100,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 100,
    },
    {
        order_number: 4,
        content_type: "list",
        content: "រចនាសម្ព័ន្ធល្អជួយឱ្យអ្នកអានយល់ពីប្រធានបទរបស់អ្នកបានយ៉ាងងាយស្រួល។",
        lessonId: 100,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការសរសេរផ្នែកពិនិត្យ",
        lessonId: 101,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "អ្នកគួរតែសង្ខេបនិងវាយតម្លៃការរកឃើញសំខាន់ៗដោយមិនគ្រាន់តែរាយបញ្ជី។ វាបង្ហាញពីការយល់ដឹងស៊ីជម្រៅរបស់អ្នក។",
        lessonId: 101,
    },
    {
        order_number: 3,
        content_type: "image",
        content: "https://picsum.photos/600/400?random=37",
        lessonId: 101,
    },
    {
        order_number: 4,
        content_type: "space",
        content: "",
        lessonId: 101,
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ត្រូវប្រាកដថាអ្នកកំណត់គម្លាតនៅក្នុងអក្សរសិល្ប៍។",
        lessonId: 101,
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបកស្រាយលទ្ធផលនៃការវិភាគតំរែតំរង់",
        lessonId: 102,
    },
    {
        order_number: 2,
        content_type: "text",
        content: "នៅពេលដែលអ្នកបានធ្វើការវិភាគតំរែតំរង់ហើយជំហានបន្ទាប់គឺការបកស្រាយលទ្ធផល។ នេះរួមបញ្ចូលទាំងការពិនិត្យមើលមេគុណតំរែតំរង់ តម្លៃ P-value និង R-squared ដើម្បីវាយតម្លៃពីគុណភាពនៃម៉ូដែល។",
        lessonId: 102,
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 102
    },
    {
        order_number: 4,
        content_type: "list",
        content: "មេគុណតំរែតំរង់៖ តើអថេរឯករាជ្យប៉ះពាល់ដល់អថេរពឹងផ្អែកយ៉ាងដូចម្តេច",
        lessonId: 102
    },
    {
        order_number: 5,
        content_type: "list",
        content: "R-squared៖ តើអថេរឯករាជ្យអាចពន្យល់ពីការប្រែប្រួលរបស់អថេរពឹងផ្អែកបានកម្រិតណា",
        lessonId: 102
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/regression_results.jpg",
        lessonId: 102
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការវិភាគតំរែតំរង់ជាច្រើន",
        lessonId: 103
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការវិភាគតំរែតំរង់ជាច្រើនអនុញ្ញាតឱ្យអ្នកប្រើអថេរឯករាជ្យច្រើនជាងមួយដើម្បីព្យាករណ៍អថេរពឹងផ្អែក។ វាជួយឱ្យយើងយល់ពីទំនាក់ទំនងស្មុគស្មាញរវាងអថេរ។",
        lessonId: 103
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 103
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ពិនិត្យមើលទំនាក់ទំនងរវាងអថេរឯករាជ្យទាំងអស់",
        lessonId: 103
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការជ្រើសរើសម៉ូដែលល្អបំផុត",
        lessonId: 103
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/multiple_regression.jpg",
        lessonId: 103
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការយល់ដឹងអំពី Correlation",
        lessonId: 104
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Correlation គឺជាការវាស់វែងពីកម្លាំងនិងទិសដៅនៃទំនាក់ទំនងរវាងអថេរពីរ។ តម្លៃនៃ correlation ស្ថិតនៅចន្លោះពី -1 និង +1 ។",
        lessonId: 104
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 104
    },
    {
        order_number: 4,
        content_type: "list",
        content: "Correlation វិជ្ជមាន៖ អថេរទាំងពីរផ្លាស់ប្តូរទៅទិសដៅដូចគ្នា",
        lessonId: 104
    },
    {
        order_number: 5,
        content_type: "list",
        content: "Correlation អវិជ្ជមាន៖ អថេរទាំងពីរផ្លាស់ប្តូរទៅទិសដៅផ្ទុយគ្នា",
        lessonId: 104
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/correlation.jpg",
        lessonId: 104
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការវិភាគទំនាក់ទំនង Chi-Square",
        lessonId: 105
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Chi-Square Test ត្រូវបានប្រើដើម្បីកំណត់ថាតើមានទំនាក់ទំនងដែលមានសារៈសំខាន់រវាងអថេរគុណភាពពីរឬអត់។",
        lessonId: 105
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 105
    },
    {
        order_number: 4,
        content_type: "list",
        content: "សម្មតិកម្ម Null៖ មិនមានទំនាក់ទំនងរវាងអថេរទាំងពីរទេ",
        lessonId: 105
    },
    {
        order_number: 5,
        content_type: "list",
        content: "P-value តិចជាងកម្រិតសារៈសំខាន់ បង្ហាញពីទំនាក់ទំនង",
        lessonId: 105
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/chisquare.jpg",
        lessonId: 105
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ SPSS",
        lessonId: 106
    },
    {
        order_number: 2,
        content_type: "text",
        content: "SPSS គឺជាកម្មវិធីដ៏មានឥទ្ធិពលសម្រាប់វិភាគស្ថិតិ។ វាមានចំណុចប្រទាក់ដែលងាយស្រួលប្រើសម្រាប់អ្នកប្រើប្រាស់គ្រប់កម្រិត។",
        lessonId: 106
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 106
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការបញ្ចូលទិន្នន័យ",
        lessonId: 106
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការរៀបចំអថេរ",
        lessonId: 106
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/spss.jpg",
        lessonId: 106
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ Stata",
        lessonId: 107
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Stata គឺជាកម្មវិធីស្ថិតិដែលពេញនិយមនៅក្នុងវិស័យសេដ្ឋកិច្ចនិងវិទ្យាសាស្ត្រសង្គម។ វាមានសមត្ថភាពវិភាគទិន្នន័យដ៏ទូលំទូលាយ។",
        lessonId: 107
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 107
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ប្រើសម្រាប់វិភាគទិន្នន័យបណ្តោះអាសន្ន",
        lessonId: 107
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការសរសេរកូដដើម្បីគ្រប់គ្រងទិន្នន័យ",
        lessonId: 107
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/stata.jpg",
        lessonId: 107
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ R",
        lessonId: 108
    },
    {
        order_number: 2,
        content_type: "text",
        content: "R គឺជាភាសាសរសេរកម្មវិធីនិងបរិយាកាសសម្រាប់ស្ថិតិនិងក្រាហ្វិក។ វាមានលក្ខណៈបត់បែនខ្ពស់និងឥតគិតថ្លៃ។",
        lessonId: 108
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 108
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការវិភាគទិន្នន័យដ៏ស្មុគស្មាញ",
        lessonId: 108
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការបង្កើតក្រាហ្វគុណភាពខ្ពស់",
        lessonId: 108
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/r.jpg",
        lessonId: 108
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ Python",
        lessonId: 109
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Python គឺជាភាសាសរសេរកម្មវិធីដែលមានប្រជាប្រិយភាពខ្ពស់សម្រាប់ការវិភាគទិន្នន័យ។ វាមានបណ្ណាល័យជាច្រើនដូចជា Pandas និង Matplotlib ។",
        lessonId: 109
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 109
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការគ្រប់គ្រងទិន្នន័យធំ",
        lessonId: 109
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការអនុវត្តម៉ូដែលសិក្សារបស់ម៉ាស៊ីន",
        lessonId: 109
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/python.jpg",
        lessonId: 109
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ Excel",
        lessonId: 110
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Excel គឺជាកម្មវិធីមួយដែលងាយស្រួលប្រើសម្រាប់វិភាគទិន្នន័យមូលដ្ឋាន។ វាស័ក្តិសមសម្រាប់អ្នកចាប់ផ្តើមដំបូង។",
        lessonId: 110
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 110
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការគណនាមធ្យមនិងគម្លាតស្តង់ដារ",
        lessonId: 110
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការបង្កើតតារាង Pivot និងក្រាហ្វ",
        lessonId: 110
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/excel.jpg",
        lessonId: 110
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការធ្វើទ្រង់ទ្រាយរបាយការណ៍",
        lessonId: 111
    },
    {
        order_number: 2,
        content_type: "text",
        content: "របាយការណ៍ដ៏ល្អគួរតែមានការរៀបចំច្បាស់លាស់ ងាយស្រួលយល់ និងមានព័ត៌មានគ្រប់គ្រាន់ដើម្បីគាំទ្រដល់ការរកឃើញ។",
        lessonId: 111
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 111
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ចំណងជើង និងសេចក្តីសង្ខេប",
        lessonId: 111
    },
    {
        order_number: 5,
        content_type: "list",
        content: "តារាងនិងក្រាហ្វ",
        lessonId: 111
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/report.jpg",
        lessonId: 111
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបង្ហាញលទ្ធផលស្រាវជ្រាវ",
        lessonId: 112
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការបង្ហាញលទ្ធផលប្រកបដោយប្រសិទ្ធភាពគឺសំខាន់ណាស់។ វារួមបញ្ចូលទាំងការប្រើប្រាស់ក្រាហ្វិកនិងការនិយាយពន្យល់ដោយសង្ខេប។",
        lessonId: 112
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 112
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ប្រើប្រាស់ក្រាហ្វដែលសមស្រប",
        lessonId: 112
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ផ្តោតលើចំណុចសំខាន់",
        lessonId: 112
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/presentation.jpg",
        lessonId: 112
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ Power BI",
        lessonId: 113
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Power BI គឺជាកម្មវិធីដ៏ពេញនិយមសម្រាប់ការបង្កើត Dashboard និងរបាយការណ៍អន្តរកម្ម។",
        lessonId: 113
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 113
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការភ្ជាប់ទិន្នន័យពីប្រភពជាច្រើន",
        lessonId: 113
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការបង្កើតក្រាហ្វិកឌីណាមិក",
        lessonId: 113
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/powerbi.jpg",
        lessonId: 113
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ Tableau",
        lessonId: 114
    },
    {
        order_number: 2,
        content_type: "text",
        content: "Tableau ត្រូវបានប្រើប្រាស់យ៉ាងទូលំទូលាយសម្រាប់ការមើលឃើញទិន្នន័យ។ វាមានលក្ខណៈពិសេសជាច្រើនសម្រាប់បង្កើត Dashboard ដែលមានគុណភាពខ្ពស់។",
        lessonId: 114
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 114
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការបង្កើតផែនទីទិន្នន័យ",
        lessonId: 114
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការបោះពុម្ពផ្សាយរបាយការណ៍លើអ៊ីនធឺណិត",
        lessonId: 114
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/tableau.jpg",
        lessonId: 114
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការប្រើប្រាស់ Excel",
        lessonId: 115
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ក្រៅពីការវិភាគមូលដ្ឋាន Excel ក៏អាចប្រើដើម្បីបង្កើត Dashboard ដែរ។",
        lessonId: 115
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 115
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការប្រើប្រាស់មុខងារ Pivot Chart",
        lessonId: 115
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការបន្ថែម Slicers ដើម្បីធ្វើអន្តរកម្ម",
        lessonId: 115
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/excel_dashboard.jpg",
        lessonId: 115
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការបោះពុម្ពផ្សាយការវិភាគរបស់អ្នក",
        lessonId: 116
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការបោះពុម្ពផ្សាយលទ្ធផលនៃការវិភាគរបស់អ្នកគឺសំខាន់សម្រាប់ចែករំលែកចំណេះដឹង។ នេះអាចជាអត្ថបទស្រាវជ្រាវ ប្លុក ឬរបាយការណ៍។",
        lessonId: 116
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 116
    },
    {
        order_number: 4,
        content_type: "list",
        content: "ការសរសេរអត្ថបទសម្រាប់ទស្សនាវដ្តី",
        lessonId: 116
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ការបង្ហោះលើគេហទំព័រផ្ទាល់ខ្លួន",
        lessonId: 116
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/publishing.jpg",
        lessonId: 116
    },
    {
        order_number: 1,
        content_type: "heading",
        content: "ការធ្វើបទបង្ហាញទៅកាន់ទស្សនិកជន",
        lessonId: 117
    },
    {
        order_number: 2,
        content_type: "text",
        content: "ការធ្វើបទបង្ហាញដោយជោគជ័យគឺទាមទារនូវការរៀបចំផែនការ និងការអនុវត្តល្អ។ ត្រូវយល់ពីទស្សនិកជនរបស់អ្នកនិងកាត់បន្ថយការប្រើប្រាស់ពាក្យបច្ចេកទេស។",
        lessonId: 117
    },
    {
        order_number: 3,
        content_type: "space",
        content: "",
        lessonId: 117
    },
    {
        order_number: 4,
        content_type: "list",
        content: "បង្កើតស្លាយដែលមើលទៅស្អាត",
        lessonId: 117
    },
    {
        order_number: 5,
        content_type: "list",
        content: "ផ្តោតលើរឿងរ៉ាវរបស់ទិន្នន័យ",
        lessonId: 117
    },
    {
        order_number: 6,
        content_type: "image",
        content: "https://example.com/images/presentation.jpg",
        lessonId: 117
    }
]

export default lessonContents