const reviews = [
  {
    reviewer_img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
    rating: 5,
    name: "ចាន់ វាសនា",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាវិភាគស្ថិតិ",
  },
  {
    reviewer_img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
    rating: 5,
    name: "ស្រី សុភា",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
    rating: 5,
    name: "ហង្ស វុទ្ធី",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាគណនាទិន្នន័យ",
  },
  {
    reviewer_img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
    rating: 5,
    name: "កែវ ចន្ទ្រា",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាសរសេរសៀវភៅស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTootEEHlY5yfLQOlUqKlZ9r1KBS-sdDMFnQ&s",
    rating: 4,
    name: "ព្រំ សុខន់",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាស្រង់ស្ថិតិ",
  },
  {
    reviewer_img: "https://storage.needpix.com/rsynced_images/profile-1719207_1280.jpg",
    rating: 5,
    name: "សំ អង្គារ",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សារបាយការណ៍ស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://images.pexels.com/photos/3184611/pexels-photo-3184611.jpeg",
    rating: 5,
    name: "ម៉ៅ សំណាង",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាវិភាគស្ថិតិ",
  },
  {
    reviewer_img: "https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg",
    rating: 5,
    name: "អ៊ុក ច័ន្ទពន្លឺ",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://t4.ftcdn.net/jpg/05/80/60/33/360_F_580603305_ysEbDBvHCKM9TyzEINHyW614NWLdTe0b.jpg",
    rating: 5,
    name: "ជូត សុវណ្ណ",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាគណនាទិន្នន័យ",
  },
  {
    reviewer_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtiYg3H2P0TLK6KWYPLThX2q8BVt6JRkSt-RWEu1Wls3IVXUXXLk-SWwAj0_M1C5Z4Iz0&usqp=CAU",
    rating: 5,
    name: "គឹម មនោរម្យ",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាសរសេរសៀវភៅស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://i.pinimg.com/736x/fc/af/a2/fcafa2726cf6f9a2ae6743a629e3e141.jpg",
    rating: 4,
    name: "លឹម ស្រីពៅ",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាស្រង់ស្ថិតិ",
  },
  {
    reviewer_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV37fEhwuGqidsvwZ26NGGg0ip3BkM31jgJZia-_WsNs9PNSzTKdsFyRkq-lwrBcnrtWY&usqp=CAU",
    rating: 5,
    name: "សួង សុភ័ក្រ",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សារបាយការណ៍ស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://t3.ftcdn.net/jpg/06/49/71/98/360_F_649719870_0KjDq1hvvnto0WfYg08Lo1os3L1OLEUW.jpg",
    rating: 5,
    name: "ឡេង វិសាល",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាវិភាគស្ថិតិ",
  },
  {
    reviewer_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4a0wfWv-DO8zS0SKNtWcxIoiAu6g03chxwA&s",
    rating: 5,
    name: "វ៉ាន់ សុធា",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាស្រាវជ្រាវ",
  },
  {
    reviewer_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMxnzxXEt0_VUiHF1meOPtI5BCGURJ9ZJIuA&s",
    rating: 5,
    name: "អៀង ច័ន្ទរដ្ឋា",
    generation: "ជំនាន់ទី ១០",
    course_name: "វគ្គសិក្សាគណនាទិន្នន័យ",
  },
];

export default reviews;
