const reviews = [
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756787873/al-pacino-042423-2000-d6fdcc99931f4a32aec8aca88b80cd40_rjl3ft.jpg',
        rating: 5,
        name: 'សុគន្ធ ឌែននី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាវិភាគស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756787878/28CILLIAN-MURPHY-01-tzqm-superJumbo_h3f334.jpg',
        rating: 5,
        name: 'មុយ មេធី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788439/image-w856.jpg_ebob0m.webp',
        rating: 5,
        name: 'វង់ រិទ្ធា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាគណនាទិន្នន័យ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788480/8ee4c2dfe45d7848da31864428c5e3d3_aelf5d.jpg',
        rating: 5,
        name: 'សុខ ប៊ុនលាភ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាសរសេរសៀវភៅស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756890389/teenage-angelina-jolie-circa-late-80s-early-90s-v0-8qq4bri2fgh81_rbbfq6.jpg',
        rating: 4,
        name: 'ប្រាក់ ពីរជ័យ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រង់ស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788498/best-popular-famous-90s-actresses-movie-television-tv-stars-women_xly1nb.jpg',
        rating: 5,
        name: 'គ្រុយ សីហា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សារបាយការណ៍ស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788499/Julia-Roberts-Actress-1990s-Far-Out-Magazine-1140x855_f5wbfc.jpg',
        rating: 5,
        name: 'សុគន្ធ ឌែននី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាវិភាគស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788500/The-Best-90s-Actor-and-Actresses-Feature.jpg_mpd9hn.jxl',
        rating: 5,
        name: 'មុយ មេធី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789584/fast-and-furious-6_0-76b82302cb75469c8b05977f94743c03_ngudj3.jpg',
        rating: 5,
        name: 'វង់ រិទ្ធា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាគណនាទិន្នន័យ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789585/MV5BMzVjNDRkMTYtMTczYS00ZTEyLWI3NTQtYTc3NWE4MTY3OGNkXkEyXkFqcGdeQWRvb2xpbmhk._V1__jzdv43.jpg',
        rating: 5,
        name: 'សុខ ប៊ុនលាភ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាសរសេរសៀវភៅស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789586/the-dark-knight.jpg_fehlvx.jpg',
        rating: 4,
        name: 'ប្រាក់ ពីរជ័យ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រង់ស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789587/Tobey.Maguire.09.1999_03_kgc07q.jpg',
        rating: 5,
        name: 'គ្រុយ សីហា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សារបាយការណ៍ស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788481/92fe2393-74b4-4568-a634-0a7e18c0ddf3.jpg_qqugde.avif',
        rating: 5,
        name: 'សុគន្ធ ឌែននី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាវិភាគស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788498/Christian_Bale_Mug_2_dinfpb.webp',
        rating: 5,
        name: 'មុយ មេធី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788499/MV5BMTc5MjgyMzk4NF5BMl5BanBnXkFtZTcwODk2OTM4Mg._V1__htgjze.jpg',
        rating: 5,
        name: 'វង់ រិទ្ធា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាគណនាទិន្នន័យ',
    },
]

export default reviews