import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const programs = [
    {
        program_title: 'ស្ថិតិ',
        slug: 'statistic',
        certificate_name: 'គ្រប់គ្រងស្ថិតិទិន្នន័យ',
        logo_url: 'https://www.ibm-institute.com/wp-content/uploads/2019/07/goal-150x150.png',
        certificate_img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756798068/Certificate_Template_zoogqk.jpg',
        duration_each_course: '២ ម៉ោងក្នុងមួយវគ្គ',
        level: 'វគ្គណែនាំ',
        additional_price: 'មិនមានចំណាយបន្ថែម',
        how_to_get: 'បើកដោយស្វ័យប្រវត្តិ បន្ទាប់ពីបញ្ចប់វគ្គសិក្សាតាមដែលត្រូវការ',
        about_text: 'កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺផ្តោតលើការអភិវឌ្ឍជំនាញអាជីវកម្មរបស់អ្នក។ វាជាកម្មវិធីសិក្សារយៈពេលខ្លីតាមប្រព័ន្ធអនឡាញ ដែលគ្របដណ្តប់លើវិស័យសំខាន់ទាំងអស់នៃការគ្រប់គ្រងអាជីវកម្មទូទៅ។ កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺជាវិធីសាស្រ្តឆាប់រហ័ស និងចំណាយតិច ដើម្បីឈានដល់គោលដៅអាជីពបន្ទាប់ និងបង្កើនប្រវត្តិការងាររបស់អ្នក។ វាបង្ហាប់ចំណុចសំខាន់ៗនៃការសិក្សាគ្រប់គ្រងប្រពៃណី ទៅជាវគ្គសិក្សាអនឡាញ ៤ ដែលគួរឱ្យរំភើប និងមានតម្លៃសមរម្យ។',
        firstDesignedFor_text: 'អ្នកចង់ទទួលបានការយល់ដឹងគ្រឹះអំពីពិភពអាជីវកម្ម និងដាក់គ្រឹះល្អសម្រាប់ផ្លូវអាជីពរបស់ខ្លួន។',
        secondDesignedFor_text: 'អ្នកគ្រប់គ្រងដែលចង់មានចំណេះដឹងទូលំទូលាយក្នុងវិស័យពាក់ព័ន្ធនឹងអាជីវកម្ម ដើម្បីអាចរីកចម្រើនក្នុងអាជីព។',
        thirdDesignedFor_text: 'អ្នកចង់ទទួលបានចំណុចសំខាន់ៗនៃការសិក្សាផ្នែកគ្រប់គ្រងក្នុងរយៈពេលលឿន និងចំណាយសមរម្យ។',
    },
    {
        program_title: 'វិភាគ',
        slug: 'analytics',
        certificate_name: 'វិភាគស្ថិតិទិន្នន័យ',
        logo_url: 'https://www.ibm-institute.com/wp-content/uploads/2019/05/career-150x150.png',
        certificate_img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756798068/Certificate_Template_zoogqk.jpg',
        duration_each_course: '២ ម៉ោងក្នុងមួយវគ្គ',
        level: 'វគ្គណែនាំ',
        additional_price: 'មិនមានចំណាយបន្ថែម',
        how_to_get: 'បើកដោយស្វ័យប្រវត្តិ បន្ទាប់ពីបញ្ចប់វគ្គសិក្សាតាមដែលត្រូវការ',
        about_text: 'កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺផ្តោតលើការអភិវឌ្ឍជំនាញអាជីវកម្មរបស់អ្នក។ វាជាកម្មវិធីសិក្សារយៈពេលខ្លីតាមប្រព័ន្ធអនឡាញ ដែលគ្របដណ្តប់លើវិស័យសំខាន់ទាំងអស់នៃការគ្រប់គ្រងអាជីវកម្មទូទៅ។ កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺជាវិធីសាស្រ្តឆាប់រហ័ស និងចំណាយតិច ដើម្បីឈានដល់គោលដៅអាជីពបន្ទាប់ និងបង្កើនប្រវត្តិការងាររបស់អ្នក។ វាបង្ហាប់ចំណុចសំខាន់ៗនៃការសិក្សាគ្រប់គ្រងប្រពៃណី ទៅជាវគ្គសិក្សាអនឡាញ ៤ ដែលគួរឱ្យរំភើប និងមានតម្លៃសមរម្យ។',
        firstDesignedFor_text: 'អ្នកចង់ទទួលបានការយល់ដឹងគ្រឹះអំពីពិភពអាជីវកម្ម និងដាក់គ្រឹះល្អសម្រាប់ផ្លូវអាជីពរបស់ខ្លួន។',
        secondDesignedFor_text: 'អ្នកគ្រប់គ្រងដែលចង់មានចំណេះដឹងទូលំទូលាយក្នុងវិស័យពាក់ព័ន្ធនឹងអាជីវកម្ម ដើម្បីអាចរីកចម្រើនក្នុងអាជីព។',
        thirdDesignedFor_text: 'អ្នកចង់ទទួលបានចំណុចសំខាន់ៗនៃការសិក្សាផ្នែកគ្រប់គ្រងក្នុងរយៈពេលលឿន និងចំណាយសមរម្យ។',
    },
    {
        program_title: 'ស្រាវជ្រាវ',
        slug: 'research',
        certificate_name: 'ស្រាវជ្រាវកម្រិតណែនាំ',
        logo_url: 'https://www.ibm-institute.com/wp-content/uploads/2019/05/target-150x150.png',
        certificate_img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756798068/Certificate_Template_zoogqk.jpg',
        duration_each_course: '២ ម៉ោងក្នុងមួយវគ្គ',
        level: 'វគ្គណែនាំ',
        additional_price: 'មិនមានចំណាយបន្ថែម',
        how_to_get: 'បើកដោយស្វ័យប្រវត្តិ បន្ទាប់ពីបញ្ចប់វគ្គសិក្សាតាមដែលត្រូវការ',
        about_text: 'កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺផ្តោតលើការអភិវឌ្ឍជំនាញអាជីវកម្មរបស់អ្នក។ វាជាកម្មវិធីសិក្សារយៈពេលខ្លីតាមប្រព័ន្ធអនឡាញ ដែលគ្របដណ្តប់លើវិស័យសំខាន់ទាំងអស់នៃការគ្រប់គ្រងអាជីវកម្មទូទៅ។ កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺជាវិធីសាស្រ្តឆាប់រហ័ស និងចំណាយតិច ដើម្បីឈានដល់គោលដៅអាជីពបន្ទាប់ និងបង្កើនប្រវត្តិការងាររបស់អ្នក។ វាបង្ហាប់ចំណុចសំខាន់ៗនៃការសិក្សាគ្រប់គ្រងប្រពៃណី ទៅជាវគ្គសិក្សាអនឡាញ ៤ ដែលគួរឱ្យរំភើប និងមានតម្លៃសមរម្យ។',
        firstDesignedFor_text: 'អ្នកចង់ទទួលបានការយល់ដឹងគ្រឹះអំពីពិភពអាជីវកម្ម និងដាក់គ្រឹះល្អសម្រាប់ផ្លូវអាជីពរបស់ខ្លួន។',
        secondDesignedFor_text: 'អ្នកគ្រប់គ្រងដែលចង់មានចំណេះដឹងទូលំទូលាយក្នុងវិស័យពាក់ព័ន្ធនឹងអាជីវកម្ម ដើម្បីអាចរីកចម្រើនក្នុងអាជីព។',
        thirdDesignedFor_text: 'អ្នកចង់ទទួលបានចំណុចសំខាន់ៗនៃការសិក្សាផ្នែកគ្រប់គ្រងក្នុងរយៈពេលលឿន និងចំណាយសមរម្យ។',
    },
    {
        program_title: 'សរសេរ',
        slug: 'writing',
        certificate_name: 'សរសេរអត្ថបទស្រាវជ្រាវ',
        logo_url: 'https://www.ibm-institute.com/wp-content/uploads/2019/05/lightbulb-280x280.png',
        certificate_img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756798068/Certificate_Template_zoogqk.jpg',
        duration_each_course: '២ ម៉ោងក្នុងមួយវគ្គ',
        level: 'វគ្គណែនាំ',
        additional_price: 'មិនមានចំណាយបន្ថែម',
        how_to_get: 'បើកដោយស្វ័យប្រវត្តិ បន្ទាប់ពីបញ្ចប់វគ្គសិក្សាតាមដែលត្រូវការ',
        about_text: 'កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺផ្តោតលើការអភិវឌ្ឍជំនាញអាជីវកម្មរបស់អ្នក។ វាជាកម្មវិធីសិក្សារយៈពេលខ្លីតាមប្រព័ន្ធអនឡាញ ដែលគ្របដណ្តប់លើវិស័យសំខាន់ទាំងអស់នៃការគ្រប់គ្រងអាជីវកម្មទូទៅ។ កម្មវិធីសិក្សាគ្រប់គ្រងអាជីវកម្ម គឺជាវិធីសាស្រ្តឆាប់រហ័ស និងចំណាយតិច ដើម្បីឈានដល់គោលដៅអាជីពបន្ទាប់ និងបង្កើនប្រវត្តិការងាររបស់អ្នក។ វាបង្ហាប់ចំណុចសំខាន់ៗនៃការសិក្សាគ្រប់គ្រងប្រពៃណី ទៅជាវគ្គសិក្សាអនឡាញ ៤ ដែលគួរឱ្យរំភើប និងមានតម្លៃសមរម្យ។',
        firstDesignedFor_text: 'អ្នកចង់ទទួលបានការយល់ដឹងគ្រឹះអំពីពិភពអាជីវកម្ម និងដាក់គ្រឹះល្អសម្រាប់ផ្លូវអាជីពរបស់ខ្លួន។',
        secondDesignedFor_text: 'អ្នកគ្រប់គ្រងដែលចង់មានចំណេះដឹងទូលំទូលាយក្នុងវិស័យពាក់ព័ន្ធនឹងអាជីវកម្ម ដើម្បីអាចរីកចម្រើនក្នុងអាជីព។',
        thirdDesignedFor_text: 'អ្នកចង់ទទួលបានចំណុចសំខាន់ៗនៃការសិក្សាផ្នែកគ្រប់គ្រងក្នុងរយៈពេលលឿន និងចំណាយសមរម្យ។',
    },
]

const courses = [
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783946/AA001-IMG_-_4_x_2.5_abvtx1.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'statistic-description',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$0.0១',
        discount_percent: '៧០%',
        title: 'ការវិភាគស្ថិតិពិពណ៌នា',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 1
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783950/AA002-IMG_-_4_x_2.5_m9hi7f.png',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'statistic-analytics',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការវិភាគស្ថិតិសន្និដ្ឋាន',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 1
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783958/AA003-IMG_-_4_x_2.5_brzlsw.png',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'regression-analytics',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការវិភាគ Regression',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 1
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783962/AA004-IMG_-_4_x_2.5_btyi7j.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'choose-leftover',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'វិធីសាស្ត្រជ្រើសរើសសំណាក',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 1
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783948/AA005-IMG_-_4_x_2.5_r63j6s.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'statistic-spss',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការវិភាគស្ថិតិតាម SPSS',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 2
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783950/AA006-IMG_-_4_x_2.5_bbtwea.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'statistic-stata',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការវិភាគស្ថិតិតាម STATA',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 2
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783947/AA007-IMG_-_4_x_2.5_hmxiij.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'statistic-r',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការវិភាគស្ថិតិតាម R',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 2
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783949/AA008-IMG_-_4_x_2.5_xb8ng4.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'statistic-excel',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការវិភាគស្ថិតិតាម Excel',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 2
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783960/AA009-IMG_-_4_x_2.5_copc5i.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'research-request',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការសរសេរសំណើរស្រាវជ្រាវ',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 3
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783974/AA010-IMG_-_4_x_2.5_genvgn.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'quantity-research',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការស្រាវជ្រាវបែបបរិមាណ',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 3
    },
    {
        img_url: 'https://connexionresearch.com/wp-content/uploads/2023/11/Qualitative-Reporting-scaled.jpeg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'quality-research',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការស្រាវជ្រាវបែបគុណភាព',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 3
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783980/AA012-IMG_-_4_x_2.5_hbk0r5.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'mixed-research',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការស្រាវជ្រាវបែប Mixed Method',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 3
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783970/AA013-IMG_-_4_x_2.5_ydcaoy.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'research-report',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'របាយការណ៍ស្រាវជ្រាវ',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 4
    },
    {
        img_url: 'https://blog.resumesolutionco.com/wp-content/uploads/2023/05/premium_photo-1661761077411-d50cba031848.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'thesis-writing',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការសរសេរនិក្ខេបបទ',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 4
    },
    {
        img_url: 'https://www.impactgroupmarketing.com/Portals/0/xBlog/uploads/2022/7/6/6ReasonstoHireaProfessionalContentWriter.jpg',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'research-writing',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការសរសេរអត្ថបទស្រាវជ្រាវ',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 4
    },
    {
        img_url: 'https://img.freepik.com/free-photo/authentic-small-youthful-marketing-agency_23-2150167350.jpg?semt=ais_hybrid&w=740&q=80',
        youtube_url: 'https://www.youtube.com/embed/YVs8xkJoKtI?si=3TUPtQQSX3EjrwXD&autoplay=1',
        certificate_type: 'សញ្ញាបត្រវគ្គសិក្សា',
        duration: '២ ម៉ោង',
        online_percent: '១០០%',
        slug: 'review-writing',
        rating: 5,
        original_price: '$៣០.០០',
        discounted_price: '$១១.៩៩',
        discount_percent: '៧០%',
        title: 'ការសរសេរ Review Paper',
        study_type: 'វគ្គសិក្សា អនឡាញ',
        language: 'ភាសាខ្មែរ',
        level: 'វគ្គណែនាំ',
        access: 'ពេញមួយជីវិត',
        introduction_text: 'ការណែនាំអំពីជំនាញសំខាន់បំផុត និងឧបករណ៍ដែលអាចអនុវត្តបានបំផុតនៃការគ្រប់គ្រងទីផ្សារ និងទំនាក់ទំនង។',
        first_skill: 'យល់ពីការយល់ដឹងអំពីទីផ្សារ',
        second_skill: 'ការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនជោគជ័យ',
        third_skill: 'ការវាយតម្លៃយុទ្ធសាស្រ្តទីផ្សារ',
        main_text: 'នៅក្នុងវគ្គសិក្សានេះ អ្នកនឹងរៀនបង្កើត ចែកចាយ និងទំនាក់ទំនងតម្លៃនៃផលិតផលទៅកាន់អតិថិជនរបស់អ្នក និងដើម្បីបង្កើតការគ្រប់គ្រងទំនាក់ទំនងអតិថិជនដ៏រឹងមាំ។',
        detail_text: 'សំណុំនៃការចូលរួមដែលចាំបាច់សម្រាប់ការគ្រប់គ្រងទីផ្សារប្រកបដោយជោគជ័យរួមមាន ការចាប់យកការយល់ដឹងអំពីទីផ្សារ ការភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជន ការកសាងម៉ាកយីហោដ៏រឹងមាំ ការរៀបចំការផ្តល់ជូនទីផ្សារ ការផ្តល់ និងទំនាក់ទំនងតម្លៃ ការបង្កើតកំណើនរយៈពេលវែង និងការអភិវឌ្ឍយុទ្ធសាស្រ្ត និងផែនការទីផ្សារ។',
        conclusion_text: 'អ្នកនឹងទទួលបានសិក្សាករណីខ្លីមួយដែលសង្ខេបយ៉ាងខ្លីអំពីចំណុចសំខាន់ៗនៃវគ្គសិក្សានេះ។',
        programId: 4
    },
]

const homeMedia = [
    {
        page: 'home',
        section: 'course_benefits',
        type: 'image',
        url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756797829/AA001-IMG_-_4_x_2.5_g2tbkf.jpg',
        alt: 'course_benefit_image',
    },
    {
        page: 'global',
        section: 'certificate_image',
        type: 'image',
        url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756798068/Certificate_Template_zoogqk.jpg',
        alt: 'certificate_sample_image',
    },
]

const slideShows = [
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783958/AA003-IMG_-_4_x_2.5_brzlsw.png',
        title: 'រៀនអំពីគោលការណ៍អនុវត្តន៍ការវិភាគស្ថិតិ និងការស្រាវជ្រាវ',
        description: 'កម្មវិធីសិក្សាបែបទំនើប ដោយផ្អែកទៅលើករិណីសិក្សាជាក់ស្តែង',
        button_message: 'ស្វែងរកវគ្គបណ្តុះបណ្តាល',
        route_link: '/courselist',
        is_active: true,
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783946/AA001-IMG_-_4_x_2.5_abvtx1.jpg',
        title: 'រៀនអំពីគោលការណ៍អនុវត្តន៍ការវិភាគស្ថិតិ និងការស្រាវជ្រាវ',
        description: 'កម្មវិធីសិក្សាបែបទំនើប ដោយផ្អែកទៅលើករិណីសិក្សាជាក់ស្តែង',
        button_message: 'ស្វែងរកវគ្គបណ្តុះបណ្តាល',
        route_link: '/courselist',
        is_active: true,
    },
    {
        img_url: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756783950/AA002-IMG_-_4_x_2.5_m9hi7f.png',
        title: 'រៀនអំពីគោលការណ៍អនុវត្តន៍ការវិភាគស្ថិតិ និងការស្រាវជ្រាវ',
        description: 'កម្មវិធីសិក្សាបែបទំនើប ដោយផ្អែកទៅលើករិណីសិក្សាជាក់ស្តែង',
        button_message: 'ស្វែងរកវគ្គបណ្តុះបណ្តាល',
        route_link: '/courselist',
        is_active: true,
    },
]

const courseOverview = {
    page: 'home',
    section: 'course_overview',
    type: 'heading',
    contents: 'យល់ច្បាស់អំពីការវិភាគស្ថិតិ និងការស្រាវជ្រាវ'
}

const courseBenefits = [
    {
        page: 'home',
        section: 'course_benefits',
        type: 'sub_heading',
        content: 'កសាងសម្ថភាពជំនាញការវិភាគទិន្នន័យ​​​ និងការស្រាវជ្រាវ'
    },
    {
        page: 'home',
        section: 'course_benefits',
        type: 'paragraph',
        content: 'វគ្គបណ្តុះបណ្តាលរបស់យើង​ ត្រូវបានរៀបចំឡើង ដោយគ្រូជំនាញជាច្រើនរូបដូច្នេះ ជំនាញដែលទទួលបាន​ នឹងជាតម្រូវការខ្ពស់របស់ស្ថាប័នការងារផ្សេងៗ។'
    },
    {
        page: 'home',
        section: 'course_benefits',
        type: 'sub_heading',
        content: 'ទទួលបានចំណេះជំនាញលឿន ទាន់ចិត្ត'
    },
    {
        page: 'home',
        section: 'course_benefits',
        type: 'paragraph',
        content: 'មាតិកាបង្រៀន មានលក្ខណះប្រមូលផ្តុំចំណុចសំខាន់ៗ ដែលអាចឲ្យអ្នកសិក្សាទទួលបាននូវចំណេះជំនាញឆាប់រហ័ស និងមានប្រសិទ្ធភាព។'
    },
    {
        page: 'home',
        section: 'course_benefits',
        type: 'sub_heading',
        content: 'កាលវិភាគសិក្សា ស្ថិតលើដៃរបស់លោកអ្នក'
    },
    {
        page: 'home',
        section: 'course_benefits',
        type: 'paragraph',
        content: 'លោកអ្នកនឹងទទួលបាននូវសិទ្ធិក្នុងការចូលរៀនក្នុងគេហទំព័រយើង អស់មួយជីវិត ដូច្នេះ អ្នកអាចកំណត់ពេលវេលា និងទីកន្លែងសិក្សា ដោយខ្លួនឯងបាន។'
    },
]

const feedbacks = [
    {
        page: 'home',
        section: 'feedback',
        type: 'heading',
        content: 'ចាប់ផ្តើមទទួលយកនូវបទពិសោធន៍ការរៀនអនឡាញថ្ងៃនេះ'
    },
    {
        page: 'home',
        section: 'feedback',
        type: 'percent',
        content: '១០០%'
    },
    {
        page: 'home',
        section: 'feedback',
        type: 'paragraph',
        content: 'រៀនអនឡានដោយខ្លួនឯង'
    },
    {
        page: 'home',
        section: 'feedback',
        type: 'percent',
        content: '១០០%'
    },
    {
        page: 'home',
        section: 'feedback',
        type: 'paragraph',
        content: 'ទទួលស្គាល់ដោយស្ថាប័នរដ្ឋនិងឯកជន'
    },
    {
        page: 'home',
        section: 'feedback',
        type: 'percent',
        content: '៩៧%'
    },
    {
        page: 'home',
        section: 'feedback',
        type: 'paragraph',
        content: 'អ្នកចូលរៀនមានភាពពេញចិត្ត'
    },
]

const certificateBenefits = [
    {
        page: 'home',
        section: 'certificate_benefits',
        type: 'sub_heading',
        content: 'ទទួលបានវិញ្ញាបនបត្របញ្ជាក់ការសិក្សា'
    },
    {
        page: 'home',
        section: 'certificate_benefits',
        type: 'paragraph',
        content: 'លោកអ្នកនឹងទទួលបាន វិញ្ញាបនបត្រឌីជីថល ដែលមានគុណភាពខ្ពស់ជាមួយនឹង លេខសម្គាល់ខ្លួន នៅបញ្ជាប់ការសិក្សា។'
    },
    {
        page: 'home',
        section: 'certificate_benefits',
        type: 'sub_heading',
        content: 'ទទួលបានព្រឹតិ្តបត្រពិន្ទុ ក្រោយពេលរៀបចប់'
    },
    {
        page: 'home',
        section: 'certificate_benefits',
        type: 'paragraph',
        content: 'លោកអ្នកនឹងទទួលបាន ព្រឹតិ្តបត្រពិន្ទុឌីជីថល ដែលមានបញ្ជាក់អំពីមាតិកា និងពេលវេលារៀនត្រឹមត្រូវច្បាស់លាស់។'
    },
    {
        page: 'home',
        section: 'certificate_benefits',
        type: 'sub_heading',
        content: 'បងើ្កតគុណភាព "ប្រវតិ្តរូបសង្ខេប" របស់លោកអ្នក'
    },
    {
        page: 'home',
        section: 'certificate_benefits',
        type: 'paragraph',
        content: 'លោកអ្នកអាចអាចពន្លេច វិញ្ញាបនបត្រ និងព្រឹត្តិបត្រពិន្ទុ ដែលទទួលបាននៅក្នុង​ "ប្រវតិ្តរូបសង្ខេប ឬ CV" ដើម្បីធ្វើការដាក់សុំចូលបម្រើការងារផ្សេងៗបាន។'
    },
]

const partners = [
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786506/Massachusetts_Institute_of_Technology-Logo.wine_whonir.png',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786901/images_lcoklo.png',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786900/326525778_871680627390339_8858503200575586550_n_ktsn4k.png',
        name: 'ស្ថាប័នជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786899/1600w-r2giuWawSvQ_sd2rx6.webp',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786903/Institute_of_Technology_of_Cambodia_logo_xlh8d9.png',
        name: 'ស្ថាប័នជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786899/Chicago-University-Logo_gpeqaz.png',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786903/NU_Logo-Png.png_zqmwro.webp',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786953/1600w-ZBxBTP6Lc-E_zyo575.webp',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756786901/George_Washington_Athletics_logo.svg_nmlts4.png',
        name: 'អន្តរជាតិ',
    },
    {
        logo_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756787152/cadt_square_logo_boundary_zsahnr.jpg',
        name: 'ស្ថាប័នជាតិ',
    },
]

const reviews = [
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756787873/al-pacino-042423-2000-d6fdcc99931f4a32aec8aca88b80cd40_rjl3ft.jpg',
        rating: 5,
        name: 'សុគន្ធ ឌែននី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាវិភាគស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756787878/28CILLIAN-MURPHY-01-tzqm-superJumbo_h3f334.jpg',
        rating: 5,
        name: 'មុយ មេធី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788439/image-w856.jpg_ebob0m.webp',
        rating: 5,
        name: 'វង់ រិទ្ធា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាគណនាទិន្នន័យ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788480/8ee4c2dfe45d7848da31864428c5e3d3_aelf5d.jpg',
        rating: 5,
        name: 'សុខ ប៊ុនលាភ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាសរសេរសៀវភៅស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756890389/teenage-angelina-jolie-circa-late-80s-early-90s-v0-8qq4bri2fgh81_rbbfq6.jpg',
        rating: 4,
        name: 'ប្រាក់ ពីរជ័យ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រង់ស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788498/best-popular-famous-90s-actresses-movie-television-tv-stars-women_xly1nb.jpg',
        rating: 5,
        name: 'គ្រុយ សីហា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សារបាយការណ៍ស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788499/Julia-Roberts-Actress-1990s-Far-Out-Magazine-1140x855_f5wbfc.jpg',
        rating: 5,
        name: 'សុគន្ធ ឌែននី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាវិភាគស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788500/The-Best-90s-Actor-and-Actresses-Feature.jpg_mpd9hn.jxl',
        rating: 5,
        name: 'មុយ មេធី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789584/fast-and-furious-6_0-76b82302cb75469c8b05977f94743c03_ngudj3.jpg',
        rating: 5,
        name: 'វង់ រិទ្ធា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាគណនាទិន្នន័យ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789585/MV5BMzVjNDRkMTYtMTczYS00ZTEyLWI3NTQtYTc3NWE4MTY3OGNkXkEyXkFqcGdeQWRvb2xpbmhk._V1__jzdv43.jpg',
        rating: 5,
        name: 'សុខ ប៊ុនលាភ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាសរសេរសៀវភៅស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789586/the-dark-knight.jpg_fehlvx.jpg',
        rating: 4,
        name: 'ប្រាក់ ពីរជ័យ',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រង់ស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756789587/Tobey.Maguire.09.1999_03_kgc07q.jpg',
        rating: 5,
        name: 'គ្រុយ សីហា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សារបាយការណ៍ស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788481/92fe2393-74b4-4568-a634-0a7e18c0ddf3.jpg_qqugde.avif',
        rating: 5,
        name: 'សុគន្ធ ឌែននី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាវិភាគស្ថិតិ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788498/Christian_Bale_Mug_2_dinfpb.webp',
        rating: 5,
        name: 'មុយ មេធី',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាស្រាវជ្រាវ',
    },
    {
        reviewer_img: 'https://res.cloudinary.com/dogwsyf81/image/upload/v1756788499/MV5BMTc5MjgyMzk4NF5BMl5BanBnXkFtZTcwODk2OTM4Mg._V1__htgjze.jpg',
        rating: 5,
        name: 'វង់ រិទ្ធា',
        generation: 'ជំនាន់ទី ១០',
        course_name: 'វគ្គសិក្សាគណនាទិន្នន័យ',
    },
]

export async function main() {
    for (const program of programs) await prisma.program.create({ data: program })
    for (const course of courses) await prisma.course.create({ data: course })
    for (const media of homeMedia) await prisma.assets.create({ data: media })
    for (const slide of slideShows) await prisma.slideShows.create({ data: slide})
    for (const benefit of courseBenefits) await prisma.siteContents.create({ data: benefit })
    for (const feedback of feedbacks) await prisma.siteContents.create({ data: feedback })
    for (const benefit of certificateBenefits) await prisma.siteContents.create({ data: benefit })
    for (const partner of partners) await prisma.partner.create({ data: partner })
    for (const review of reviews) await prisma.reviews.create({ data: review })
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.log(e)
        await prisma.$disconnect()
        process.exit(1)
    })